src/components/LeftNav/LeftNavFlyout.tsx

When you have a scrollbar on a flyout (a) of a flyout (b) the flyout (b) closes onScroll.
https://www.screencast.com/t/T8pk4NB1nnk - issue that is being fixed.

Fix Flyout of a Flyout onScroll

---

src/Forms/Form/Form.stories.mdx
src/Forms/Form/formUtils.ts

Added documentation for
- The useForm hook.
- Validators.
- Form props.
- Types needed (e.g. MosaicObject).
- Sizes.

Forms documentation

---

src/Forms/Form/Form.stories.mdx
src/index.ts

- Added documentation for data and all places where it gets manipulated
- Improved documentation for validators
- Improved documentation for formActions
- Added import examples on Forms

Data documentation

---

src/forms/Form/Form.stories.mdx
src/forms/Form/Form.stories.tsx

- Update Form playground for the Advance Selection component createNewOption definition
- Update Advance Selection documentation

MOS-647: Update advance selection Form playground and docs

---

README.md
src/forms/FormFieldChipSingleSelect/FormFieldChipSingleSelect.stories.mdx

- Removed Globant fork references

MOS-651: remove Globant fork ref

---

src/components/Button/Button.styled.ts

- Added opacity to buttons type text backgraund, when they are focus

MOS-653: Glitchy text editor field in DataView

---

src/forms/Form/Col.tsx

- Deleted switch case from Col.tsx in charge of adding the asterisk to all fields marked as required.

Deleted "required checking" failsafe

---

src/forms/Form/validators.ts

- Updated validators' file to work as it used to before making them more robust.

Reverted "robust validators" functionality

---

src/components/Button/Button.styled.ts
src/components/Button/ButtonKitchenSink.tsx
src/components/Button/ButtonTypes.tsx
src/theme/theme.ts

- White icon button variant added

MOS-283: White Icon button variant added

---

src/components/DataView/DataViewActionsButtonRow.tsx
src/components/DataView/DataViewDisplayList.jsx
src/components/DataView/tests/DataViewActionsButtonRow.test.tsx
src/components/internal/GridTBody.jsx
src/components/internal/GridTr.jsx
src/transforms/column_transforms.ts

- The transformed data that was sent to the primary and additional actions callbacks was replaced by the original data of the row
- Unit tests for the `DataViewActionsButtonRow` component

MOS-150: Send original data to click callbacks

---

.storybook/main.js
src/forms/Form/Form.stories.tsx
src/forms/Form/Form.styled.ts
src/forms/FormFieldDate/DateField/DateField.test.tsx
src/forms/FormFieldDate/DateField/FormFieldDate.tsx
src/forms/FormFieldDate/DatePicker/DatePicker.styled.tsx
src/forms/FormFieldDate/DatePicker/DatePicker.tsx
src/forms/FormFieldDate/DatePicker/DatePickerTypes.tsx
src/forms/FormFieldDate/TimePicker/TimePicker.styled.tsx
src/forms/FormFieldDate/TimePicker/TimePicker.tsx
src/forms/TopComponent/Views/DesktopView.tsx
src/forms/TopComponent/Views/MobileView.tsx
src/forms/TopComponent/Views/ResponsiveView.tsx

- The update of the Time and Date picker following the migration guide https://mui.com/material-ui/guides/pickers-migration/ and applying our color styles

MOS-660/updates-date-time-mui-pickers

---

src/forms/Form/Form.stories.tsx
src/forms/FormFieldChipSingleSelect/FormFieldChipSingleSelect.tsx

- Updated Form.stories.tsx Playground story to include prepopulated data for every field.
-  Updated ChipSingleSelect field to receive prepopulated values.
- ImageUpload component (can't do it without a service to actually upload images like S3).
- DateField (the story is prepared for it, but needs an update which is already being worked on #108)

Prepopulated all fields

---

src/components/Navigation/Navigation.stories.mdx
src/components/Navigation/Navigation.stories.tsx
src/components/Navigation/Navigation.styled.tsx
src/components/Navigation/Navigation.test.tsx
src/components/Navigation/Navigation.tsx
src/components/Navigation/NavigationTypes.ts
src/components/Navigation/index.ts
src/index.ts

- Navigation component according to https://xd.adobe.com/view/91b10cca-d20f-48d4-9afc-6fe6f5b06ed5-c4e2/screen/cd022a49-5368-41f4-9149-03ddcf9d0190/specs/
- Its corresponding storybook stories
- Unit tests

MOS-671: Summary page navigation

---

src/components/Drawer.jsx
src/components/Drawers/Drawers.stories.mdx
src/components/Drawers/Drawers.stories.tsx
src/components/Drawers/Drawers.test.tsx
src/components/Drawers/Drawers.tsx
src/components/Drawers/DrawersTypes.ts
src/components/Drawers/example/ExampleTypes.ts
src/components/Drawers/example/Grid.tsx
src/components/Drawers/example/Page.tsx
src/components/Drawers/example/utils.ts
src/components/Drawers/index.ts
src/forms/FormFieldChipSingleSelect/FormFieldChipSingleSelect.test.tsx
src/forms/FormFieldChipSingleSelect/FormFieldChipSingleSelect.tsx

- New Drawers component that allows devs to stack drawers.
- Types file.
- Storybook example.

Advanced Drawer System

---

src/components/SideNav/SideNav.styled.tsx

- Fixed styles for sideNav component

MOS-671: Fix sideNav styles

---

src/components/Content/Content.stories.tsx
src/components/Content/Content.styled.tsx
src/components/Content/Content.test.tsx
src/components/Content/Content.tsx

- Fixes the following pending specs found by QA

MOS-672: Fixes missing specs for the Content component

---

src/components/DataViewPrimaryFilter.jsx
src/components/FilterSingleSelect/FilterSingleSelect.stories.mdx
src/components/FilterSingleSelect/FilterSingleSelect.stories.tsx
src/components/FilterSingleSelect/FilterSingleSelect.tsx
src/components/FilterSingleSelect/FilterSingleSelectTypes.ts

- Added bold tags to Bodytext for DataViewPrimaryFilter
- Added required validation to filterSingleSelect

MOS-682: Fix 'any' in the DateFilter

---

src/components/DataView/DataViewActionsButtonRow.tsx
src/components/DataView/DataViewBulkActionsButtonsRow.tsx
src/components/DataView/DataViewTypes.ts
src/components/DataView/utils/bulkActionsUtils.ts

- Extracted filterAction function to an external file for reusage.
- Updated DataViewActionsButtonRow and DataViewBulkActionsButtonRow files to use filterAction function.
- Updated types for show prop.

Mos 678: Run bulk actions through show function

---

src/components/Popover/Popover.stories.mdx
src/components/Popover/Popover.stories.tsx
src/components/Popover/Popover.styled.tsx
src/components/Popover/Popover.test.tsx
src/components/Popover/Popover.tsx
src/components/Popover/PopoverTypes.ts
src/components/Popover/index.ts

- Popover component 
- Storybook examples based on https://xd.adobe.com/view/91b10cca-d20f-48d4-9afc-6fe6f5b06ed5-c4e2/screen/00e4c753-5751-4a62-b826-8580fb99e285/
- Unit tests

MOS-674: Popover

---

src/forms/Form/Form.stories.mdx
src/forms/FormFieldImageVideoLinkDocumentBrowsing/ImageVideoLinkDocumentBrowsingUtils.ts

- Improves setters code example.
- Improves the documentation of the “options” prop.
- Fix documentation about the return type value-

MOS-646: Improves the documentation of the FormFieldImageVideoLinkDocument component.

---

src/components/DataViewPrimaryFilter.jsx
src/components/FilterDate/FilterDate.tsx

- Value of filters is no longer capitalized

MOS-700: Value of filters should not be capitalized

---

src/forms/FormFieldDate/DateField/FormFieldDate.tsx

- Removes the helper text from both the Date and Time field.

MOS-707: Removes helper text from date field

---

src/components/DataView/DataViewDisplayGrid.jsx

#What's include?
- Added media queries with the theme brakpoints

Mos-701: Dataview grid view

---

src/components/internal/DataViewFilters.jsx

- Searching functionality on the "More" filter.

MOS-314: Search more in filters

---

src/forms/Form/Form.tsx
src/forms/FormFieldAddress/Address.test.tsx
src/utils/useWindowResizer.ts

Fix the delay that the TopComponent was having with the initial render. This was because the initial view of the TopComponent was set to null and only after defining the view the component was rendered. The fix consists of giving it an initial view based on the screen width.

MOS-703: Form first loads fields and then the TopComponent

---

src/components/SummaryPageTopComponent/SummaryPageTopComponent.tsx

- Added extra conditional for when main and additional actions are undefined.

Fixed bug with main and additional actions on summary page top component

---

src/components/Drawers/example/Page.tsx
src/forms/Form/Form.stories.mdx
src/forms/Form/Form.stories.tsx
src/forms/Form/Form.tsx
src/forms/Form/formActions.ts
src/forms/Form/formUtils.ts
src/forms/FormFieldAddress/Address.stories.tsx
src/forms/FormFieldAddress/Address.test.tsx
src/forms/FormFieldAddress/AddressDrawer/AddressDrawer.tsx
src/forms/FormFieldAdvancedSelection/AdvancedSelection.stories.tsx
src/forms/FormFieldAdvancedSelection/AdvancedSelection.test.tsx
src/forms/FormFieldAdvancedSelection/AdvancedSelectionDrawer.tsx
src/forms/FormFieldCheckbox/FormFieldCheckbox.stories.tsx
src/forms/FormFieldChipSingleSelect/FormFieldChipSingleSelect.stories.tsx
src/forms/FormFieldChipSingleSelect/FormFieldChipSingleSelect.test.tsx
src/forms/FormFieldColorPicker/ColorPicker.stories.tsx
src/forms/FormFieldDate/DateField/DateField.stories.tsx
src/forms/FormFieldDropdownSingleSelection/FormFieldDropdownSingleSelection.stories.tsx
src/forms/FormFieldImageUpload/FormFieldImageUpload.stories.tsx
src/forms/FormFieldImageVideoLinkDocumentBrowsing/ImageVideoLinkDocumentBrowsing.stories.tsx
src/forms/FormFieldImageVideoLinkDocumentBrowsing/ImageVideoLinkDocumentBrowsing.test.tsx
src/forms/FormFieldMapCoordinates/MapCoordinates.stories.tsx
src/forms/FormFieldMapCoordinates/MapCoordinates.test.tsx
src/forms/FormFieldMapCoordinates/MapCoordinatesDrawer/MapCoordinatesDrawer.tsx
src/forms/FormFieldPhoneSelectionDropdown/FormFieldPhoneSelectionDropdown.stories.tsx
src/forms/FormFieldRadio/FormFieldRadio.stories.tsx
src/forms/FormFieldTable/Table.stories.tsx
src/forms/FormFieldText/FormFieldText.stories.tsx
src/forms/FormFieldTextArea/FormFieldTextArea.stories.tsx
src/forms/FormFieldToggleSwitch/FormFieldToggleSwitch.stories.tsx

- Removes fields registration from the Form contract
- Docs updated
- Fields are now registered within the Form component

MOS-702: Simplify form contract

---

src/components/DataView/DataViewActionsButtonRow.tsx

- Added More Actions tooltip to additionalActions button in DataView

MOS-262: Add tooltip

---

src/components/DataView/example/DataViewKitchenSink.tsx
src/components/DataViewFilterMultiselect.jsx
src/components/FilterSingleSelect/FilterSingleSelect.tsx
src/forms/FormFieldAddress/AddressDrawer/AddressDrawer.tsx
src/forms/FormFieldAdvancedSelection/AdvancedSelectionDrawer.tsx
src/forms/FormFieldMapCoordinates/MapCoordinatesDrawer/MapCoordinatesDrawer.tsx

- Checks added to only perform async operations if the component is still mounted.

MOS-716: Unmounted state update warnings

---

src/components/FilterDate/FilterDateDropdownContent.tsx
src/forms/FormFieldDate/DatePicker/DatePicker.tsx
src/forms/FormFieldDate/DatePicker/DatePickerTypes.tsx

- Update DataView Date Filter to use DatePicker of mui v5

MOS-722: Update data view date filter to mui v5

---

src/components/DataView/DataViewDisplayGrid.jsx
src/components/DataView/example/DataViewKitchenSink.tsx
src/components/internal/GridTHead.jsx
src/components/internal/GridTr.jsx

A check to not display the bulk actions of the DataView if they are undefined or an empty array.

MOS-631: Hide  bulk actions when its value is an empty array

---

automation_testing/pages/FormFields/FormFieldCheckboxPage.ts
automation_testing/tests/FormFields/formFieldCheckbox.spec.ts

https://simpleviewtools.atlassian.net/browse/MOS-728
- Added tests for the FormFieldCheckbox and all of its variants inside a Form.

MOS-728 - TAE FormFieldCheckbox

---

automation_testing/pages/FormFields/FormFieldRadioPage.ts
automation_testing/tests/FormFields/formFieldRadio.spec.ts

https://simpleviewtools.atlassian.net/browse/MOS-726
- Added tests for the FormFieldRadio and all of its variants inside a Form.

MOS-726 - TAE FormFieldRadio

---

automation_testing/pages/FormFields/FormFieldToggleSwitchPage.ts
automation_testing/tests/FormFields/formFieldToggleSwitch.spec.ts

https://simpleviewtools.atlassian.net/browse/MOS-727
- Added tests for the FormFieldToggleSwitch and all of its variants inside a Form.

MOS-727 - TAE FormFieldToggleSwitch

---

src/components/DataView/example/DataViewKitchenSink.tsx
src/utils/JSONDB.js

- Fixed filter for Categories with Comparisons - "Not In" Filter Not Filtering Items

MOS-57: Categories with Comparisons - "Not In"

---

src/components/internal/DataViewViewControls.jsx
src/components/internal/DataViewViewSaveDrawerContent.jsx

- Resets the SaveView drawer every time a view is saved.

MOS-272: Reset Save View drawer when a view is saved

---

src/components/DataView/example/DataViewKitchenSink.tsx

- When the view that is currently in use is deleted the user will use the default view.

MOS-289: Deleting a view holds onto the view name in the dropdown

---

automation_testing/pages/Components/Form/PlaygroundPage.ts
automation_testing/pages/FormFields/FormFieldDateFieldPage.ts
automation_testing/tests/FormFields/formFieldCheckbox.spec.ts
automation_testing/tests/FormFields/formFieldDateField.spec.ts
automation_testing/tests/FormFields/formFieldToggleSwitch.spec.ts
automation_testing/utils/helpers/dateHelper.ts
automation_testing/utils/helpers/helper.ts

https://simpleviewtools.atlassian.net/browse/MOS-735
- Added tests for FormFieldDateField
- Added a new helper: Date Helper

MOS-735 - TAE FormFieldDateField

---

automation_testing/pages/FormFields/FormFieldDropdownSingleSelectionPage.ts
automation_testing/tests/FormFields/formFieldDropdownSingleSelection.spec.ts

https://simpleviewtools.atlassian.net/browse/MOS-736
- Added tests for FormFieldDropdownSingleSelection

MOS-736 - TAE FormFieldDropdownSingleSelection

---

automation_testing/pages/FormFields/FormFieldImageUploadPage.ts
automation_testing/tests/FormFields/formFieldImageUpload.spec.ts

https://simpleviewtools.atlassian.net/browse/MOS-737
- Added tests for Image Upload

MOS-737 - TAE FormFieldImageUpload

---

src/forms/Form/Col.tsx
src/forms/Form/formActions.ts
src/forms/FormFieldAddress/FormFieldAddress.tsx
src/forms/FormFieldAdvancedSelection/FormFieldAdvancedSelection.tsx
src/forms/FormFieldImageVideoLinkDocumentBrowsing/ImageVideoLinkDocumentBrowsing.styled.tsx
src/forms/FormFieldImageVideoLinkDocumentBrowsing/ImageVideoLinkDocumentBrowsingUtils.ts
src/forms/FormFieldMapCoordinates/FormFieldMapCoordinates.tsx
src/forms/FormFieldTable/tableUtils.ts
src/forms/FormFieldTextEditor/FormFieldTextEditor.tsx

- onBlur was commented and added timer to onchange for validations

MOS-704: Form submit issue

---

automation_testing/pages/FormFields/FormFieldColorPickerPage.ts
automation_testing/tests/FormFields/formFieldColorPicker.spec.ts
automation_testing/utils/helpers/helper.ts

Jira Ticket:
https://simpleviewtools.atlassian.net/browse/MOS-734
What's Included:
- Added tests for FormFieldColorPicker

MOS-734 - TAE FormFieldColorPicker

---

automation_testing/pages/FormFields/FormFieldChipSingleSelectPage.ts
automation_testing/tests/FormFields/formFieldChipSingleSelect.spec.ts

https://simpleviewtools.atlassian.net/browse/MOS-733
- Added tests for FormFieldChipSingleSelect

MOS-733 - TAE FormFieldChipSingleSelect

---

src/components/DataView/DataViewTypes.ts
src/components/DataView/example/DataViewKitchenSink.tsx

- Check which DataView props are required and mark them as so.

Mos 717: Improper required fields for data view

---

automation_testing/pages/FormFields/FormFieldTablePage.ts
automation_testing/tests/FormFields/formFieldTable.spec.ts

https://simpleviewtools.atlassian.net/browse/MOS-747
- Added tests for FormFieldTable

MOS-747 - TAE FormFieldTable

---

automation_testing/pages/BasePage.ts
automation_testing/pages/FormFields/FormFieldImageVideoLinkDocumentBrowsingPage.ts
automation_testing/tests/FormFields/formFieldImageVideoLinkDocumentBrowsing.spec.ts

https://simpleviewtools.atlassian.net/browse/MOS-745
- Added tests for FormFieldImageVideoLinkDocumentBrowsing

MOS-745 - TAE FormFieldImageVideoLinkDocumentBrowsing

---

automation_testing/pages/BasePage.ts
automation_testing/pages/FormFields/FormFieldPhoneSelectionDropdownPage.ts
automation_testing/tests/FormFields/formFieldPhoneSelectionDropdown.spec.ts

https://simpleviewtools.atlassian.net/browse/MOS-748
- The objective of this ticket is to test the FormFieldPhoneSelectionDropdown and all of its variants inside a Form.

MOS-748 - TAE FormFieldPhoneSelectionDropdown

---

src/components/CheckboxList/CheckboxList.tsx
src/components/CheckboxList/CheckboxListTypes.ts
src/components/Field/FieldTypes.tsx
src/forms/Form/Form.stories.mdx
src/forms/Form/Form.stories.tsx
src/forms/FormFieldAdvancedSelection/AdvancedSelection.stories.tsx
src/forms/FormFieldAdvancedSelection/AdvancedSelection.styled.tsx
src/forms/FormFieldAdvancedSelection/AdvancedSelection.test.tsx
src/forms/FormFieldAdvancedSelection/AdvancedSelectionDrawer.tsx
src/forms/FormFieldAdvancedSelection/AdvancedSelectionTypes.tsx
src/forms/FormFieldAdvancedSelection/ChipList.tsx
src/forms/FormFieldAdvancedSelection/FormFieldAdvancedSelection.tsx
src/forms/FormFieldAdvancedSelection/advancedSelectionUtils.ts
src/forms/FormFieldCheckbox/FormFieldCheckbox.styled.ts
src/forms/FormFieldCheckbox/FormFieldCheckbox.tsx
src/forms/TopComponent/TopComponent.styled.ts

- Save value as MosaicLabelValue[ ]
- getSelected inputSetting removed
- checkboxOptions renamed to options
- Filtering fix

MOS-741: Issues with advanced selection field

---

src/forms/FormFieldDate/TimePicker/TimePicker.tsx

- Commented onBlur() from timePicker

MOS-765: onBlur errors when using Date and Time Fields

---

src/forms/FormFieldAddress/AddressCard/AddressCard.styled.tsx
src/forms/FormFieldAddress/AddressDrawer/AddressDrawer.tsx
src/forms/FormFieldAddress/FormFieldAddress.tsx

- Removed last line of the buttons of the Address card
- Changed address card width to 300px
- Fixed issues with amount per address types
- Word break to address cards (limited to 2 lines)

Mos 738: address field updates

---

src/components/Form/Col.tsx
src/forms/FormFieldAddress/FormFieldAddress.tsx
src/forms/FormFieldAdvancedSelection/AdvancedSelectionDrawer.tsx
src/forms/FormFieldAdvancedSelection/FormFieldAdvancedSelection.tsx
src/forms/FormFieldDate/DateField/DateField.test.tsx
src/forms/FormFieldDropdownSingleSelection/FormFieldDropdownSingleSelection.tsx
src/forms/FormFieldMapCoordinates/MapCoordinatesDrawer/MapCoordinatesDrawer.tsx
src/forms/FormFieldRadio/FormFieldRadio.tsx
src/forms/FormFieldText/FormFieldText.test.tsx
src/forms/FormFieldText/FormFieldText.tsx

- Changing the default value set in the Col component to each FormField.

MOS-179: Update default value in FormFields

---

src/forms/FormFieldDate/DatePicker/DatePicker.styled.tsx

- Updated paddings next to icons (clock and calendar).
- Updated colors in current date.
- Updated paddings around month.

Updated styles for date and time pickers

---

src/components/Chip/Chip.styled.ts
src/forms/FormFieldAdvancedSelection/AdvancedSelection.styled.tsx
src/forms/FormFieldAdvancedSelection/AdvancedSelectionDrawer.tsx
src/forms/FormFieldDate/DatePicker/DatePicker.styled.tsx
src/forms/TopComponent/TopComponent.styled.ts

- Updated to the styles of the search field in advanced selection component.
- Updated drawer paddings.
- Updated deletable chip's icons colors and sizes.

Mos 741 Updated styling for advanced selection component

---

src/forms/FormFieldColorPicker/ColorPicker.stories.tsx

- Updated FormFieldColorPicker stories' height to make the color picker component clickable.

Fixed FormFieldColorPicker stories height

---

src/forms/FormFieldAdvancedSelection/AdvancedSelection.styled.tsx
src/forms/FormFieldAdvancedSelection/AdvancedSelectionDrawer.tsx

- Fixed styling issue when creating new option in advanced selection.

Fixed styling issue when creating new option in advanced selection

---

changelog.md
src/components/Form/Form.stories.mdx
src/forms/FormFieldAdvancedSelection/AdvancedSelection.stories.tsx
src/forms/FormFieldAdvancedSelection/AdvancedSelectionDrawer.tsx
src/forms/FormFieldAdvancedSelection/AdvancedSelectionTypes.tsx

- Updated createOption prop in FormFieldAdvancedSelection.
- Updated FormFieldAdvancedSelection stories.
- Updated creation of new option logic in FormFieldAdvancedSelection.
- Updated Form readme with these new changes.

Fixed duplication bug

---

src/components/Form/Form.stories.mdx

- Paired fields explained further
- Example added to the validateDateRange section

MOS-778: Improve paired fields documentation

---

src/forms/FormNav/FormNav.tsx

- Adds maxWait to the navHighlighter function. The maxWait option works by adding a second timer which will fire if the normal debounce timer does not get called.

MOS-773: Fix fast scrolling that highlights the sections

---

automation_testing/pages/Components/Button/ButtonPage.ts
automation_testing/tests/Components/Button/button.spec.ts
src/components/Button/Button.styled.ts

- Button font weight is now bold

MOS-799: Update button to be font weigh 700

---

automation_testing/pages/FormFields/FormFieldAdvancedSelectionPage.ts
automation_testing/tests/FormFields/formFieldAdvancedSelection.spec.ts
src/forms/FormFieldAdvancedSelection/AdvancedSelection.test.tsx
src/forms/FormFieldAdvancedSelection/FormFieldAdvancedSelection.tsx

- Updated AdvanceSelection button from "Add Element" to "ADD"

MOS-807: Update AdvancedSelection field's button

---

automation_testing/pages/BasePage.ts
automation_testing/tests/FormFields/formFieldPhoneSelectionDropdown.spec.ts
src/forms/FormFieldPhoneSelectionDropdown/FormFieldPhoneSelectionDropdown.test.tsx
src/forms/FormFieldPhoneSelectionDropdown/FormFieldPhoneSelectionDropdown.tsx

Sets the country code edit option to false

MOS-762: Country code editable set to false

---

automation_testing/tests/Components/dataview/advanced_filters.spec.ts
src/components/DataViewFilterDropdownButtons/DataViewFilterDropdownButtons.styled.tsx
src/components/DataViewFilterDropdownButtons/DataViewFilterDropdownButtons.tsx

- Changes the styles of the buttons bar of every DataView filter.

MOS-793: Data view filter date design

---

automation_testing/tests/Components/form/playground.spec.ts
src/components/Form/validators.ts

- Updated required validator to not show an error if the value of a Field is false.

MOS-811: Required validator throws error in ToggleSwitch with false value

---

src/components/Form/Form.stories.tsx
src/forms/FormNav/FormNav.test.tsx
src/forms/FormNav/FormNav.tsx
src/forms/TopComponent/TopComponent.test.tsx
src/forms/TopComponent/Views/DesktopView.tsx
src/forms/TopComponent/Views/ResponsiveView.tsx

#What's include?
-Updated form nav logic so tabnav is not displayed when it receives one section
-Added knob to show one or three sections on the form

MOS-808: Update FormNav tabs logic

---

src/index.ts

- Now exporting Popover component in index.ts

Exporting Popover component

---

src/components/Popover/Popover.styled.tsx

Removes tiny black dot presented at the left edge of the ``<hr/>`` element

MOS-821: Updates to popover

---

src/forms/FormFieldAdvancedSelection/AdvancedSelectionDrawer.tsx
src/forms/FormFieldCheckbox/FormFieldCheckbox.tsx

- Updated checkboxList field in AdvancedSelectionDrawer to change between options and getOptions depending on the origin.

Fixed issue with getOptions on advancedSelection

---

automation_testing/pages/Components/Checkbox/CheckboxPage.ts
automation_testing/pages/FormFields/FormFieldCheckboxPage.ts
automation_testing/tests/Components/Checkbox/checkbox.spec.ts
automation_testing/tests/FormFields/formFieldCheckbox.spec.ts
src/components/Checkbox/Checkbox.styled.ts
src/components/Checkbox/Checkbox.test.tsx
src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/CheckboxTypes.tsx

- Updates checkbox label's color
- Removes helperText prop and render
- Removes helperText unit test

MOS-819: Design updates to checkbox

---

automation_testing/pages/BasePage.ts
automation_testing/pages/Components/Button/ButtonPage.ts
automation_testing/tests/Components/Button/button.spec.ts
src/components/Button/Button.styled.ts

- Increase space between the right or left icon and the button's text.

MOS-812: Update gaps between icon and text buttons

---

src/forms/FormFieldAddress/AddressCard/AddressCard.styled.tsx

Updates to the AddressCard styles

MOS-827: Updates AddressCard styles

---

automation_testing/pages/BasePage.ts
automation_testing/pages/Components/SummaryPageTopComponent/SummaryPageTopComponentPage.ts
automation_testing/tests/Components/SummaryPageTopComponent/summaryPageTopComponent.spec.ts
src/components/SummaryPageTopComponent/SummaryPageTopComponent.stories.tsx
src/components/SummaryPageTopComponent/SummaryPageTopComponent.styled.tsx
src/theme/theme.ts

-  Updates summary page top component

Mos 824: Updates to SummaryPageTopComponent

---

automation_testing/pages/BasePage.ts
automation_testing/tests/Components/Button/button.spec.ts
automation_testing/tests/Components/form/playground.spec.ts
src/forms/TopComponent/Utils/TitleWrapper.tsx
src/theme/theme.ts

MOS-825: updated top component

---

src/components/Checkbox/Checkbox.stories.tsx
src/components/SummaryPageTopComponent/SummaryPageTopComponent.stories.tsx
src/components/SummaryPageTopComponent/SummaryPageTopComponent.test.tsx
src/components/SummaryPageTopComponent/SummaryPageTopComponent.tsx
src/components/SummaryPageTopComponent/SummaryPageTopComponentTypes.ts

- Removed filter of the summaryPageTopComponent

MOS-815: Summary Top Bar Component Filter Requirement

---

automation_testing/tests/Components/dataview/advanced_filters.spec.ts
src/components/DataView/example/DataViewKitchenSink.tsx
src/utils/JSONDB.ts

- Fixed exists and not_exists filters in tittle with comparisons filter

MOS-804: Not exists filter returns all records including those with title

---

automation_testing/pages/FormFields/FormFieldImageVideoLinkDocumentBrowsingPage.ts
automation_testing/tests/FormFields/formFieldImageVideoLinkDocumentBrowsing.spec.ts
src/forms/FormFieldImageVideoLinkDocumentBrowsing/FormFieldImageVideoLinkDocumentBrowsing.tsx
src/forms/FormFieldImageVideoLinkDocumentBrowsing/ImageVideoLinkDocumentBrowsing.styled.tsx

- Updated imageVideoLinkDocumentBrowsing component

MOS-826: Updates to ImageVideoDocumentLinkSetup component

---

automation_testing/pages/BasePage.ts
automation_testing/pages/FormFields/FormFieldTextPage.ts
automation_testing/tests/FormFields/formFieldText.spec.ts
src/components/Field/InstructionText.styled.ts
src/forms/FormFieldDate/DatePicker/DatePicker.styled.tsx
src/forms/FormFieldDropdownSingleSelection/FormFieldDropdownSingleSelection.styled.tsx
src/forms/FormFieldText/FormFieldText.styled.tsx
src/forms/FormFieldTextArea/FormFieldTextArea.styled.tsx

- Hover fields and instruction text height updated

MOS-820: [DESIGN] Updates to fields

---

automation_testing/pages/Components/Button/ButtonPage.ts
automation_testing/tests/Components/Button/button.spec.ts
src/components/Button/Button.tsx
src/components/Button/ButtonKitchenSink.tsx
src/components/Button/ButtonTypes.tsx

- Button with popover set to allow closing and opening when hovering over.
- Kitchen sink examples added

MOS-816: Button popover to allow hovering

---

src/theme/theme.ts

Color updated according to the names and values defined at Figma. https://www.figma.com/file/Uba9eKQBJklt1YNJLJ3fzd/SimpleView-Components

MOS-800: Colors mapped against figma

---

automation_testing/pages/Components/SideNav/SideNavPage.ts
automation_testing/tests/Components/SideNav/sideNav.spec.ts
src/components/SideNav/SideNav.stories.tsx
src/components/SideNav/SideNav.test.tsx
src/components/SideNav/SideNav.tsx
src/components/SideNav/SideNavTypes.ts

- Updated default link active on sideNav

MOS-834: Side Nav - Active Updates

---

src/components/DataView/DataViewFilters.tsx

Use an array of strings for the activeFilters prop.

MOS-831: DataView activeFilters typing

---

src/components/Field/FieldTypes.tsx
src/components/Form/Col.tsx
src/forms/FormFieldAdvancedSelection/AdvancedSelection.styled.tsx
src/forms/FormFieldAdvancedSelection/AdvancedSelectionDrawer.tsx
src/forms/FormFieldAdvancedSelection/ChipList.tsx
src/forms/FormFieldAdvancedSelection/LoadMoreButton.tsx

#What's include?
- Design updates to AdvanceSelection component

MOS-828: Updates to advanced selection

---

automation_testing/tests/Components/Button/button.spec.ts

Jira Ticket:
https://simpleviewtools.atlassian.net/browse/MOS-839
What's Included:
The PR objective is to add a test to validate that darkSimplyGold is being used when hovering a button.

MOS-839 - Update all references to darkerSimplyGold

---

automation_testing/pages/Components/Popover/PopoverPage.ts
automation_testing/pages/FormFields/FormFieldImageUploadPage.ts
automation_testing/pages/FormFields/FormFieldImageVideoLinkDocumentBrowsingPage.ts
automation_testing/tests/Components/Button/button.spec.ts
automation_testing/tests/Components/Popover/popover.spec.ts
automation_testing/tests/FormFields/formFieldColorPicker.spec.ts
automation_testing/tests/FormFields/formFieldImageUpload.spec.ts
automation_testing/tests/FormFields/formFieldImageVideoLinkDocumentBrowsing.spec.ts
src/components/Button/Button.styled.ts
src/components/Field/Label.tsx
src/components/Popover/Popover.stories.tsx
src/components/Snackbar/Snackbar.styled.tsx
src/forms/FormFieldColorPicker/FormFieldColorPicker.tsx
src/forms/FormFieldDate/DatePicker/DatePicker.styled.tsx
src/forms/FormFieldDate/TimePicker/TimePicker.styled.tsx
src/forms/FormFieldImageUpload/FormFieldImageUpload.styled.ts
src/forms/FormFieldImageVideoLinkDocumentBrowsing/ImageVideoLinkDocumentBrowsing.styled.tsx
src/theme/theme.ts

Updates references of the blueTeal color, now is using realTeal with its opacity variants.
- Buttons (text variants)
- Label info icon of FormFields
- Text and Links Popover variant
- Snackbar icon
- Date and Time pickers
- FormFieldImageUpload
- ImageVideoLinkDocumentBrowsing

MOS-840: Replace references of blueTeal with realTeal

---

automation_testing/tests/Components/Button/button.spec.ts
src/components/DataView/DataViewTBody.tsx
src/components/Dialog/Dialog.stories.tsx
src/components/Dialog/Dialog.test.tsx
src/components/Dialog/Dialog.tsx
src/components/Dialog/DialogTypes.tsx
src/components/Form/Form.tsx

- Allows the Dialog component to receive a list of buttons as a prop.
- Unit tests updated
- Form dialog updated to use the new buttons sintaxis

MOS-862: Update the dialog component with dynamic buttons

---

src/components/Button/Button.styled.ts

- Updated all references to darkerRealTeal

MOS-841: Update all references to darkerRealTeal

---

src/components/Field/Field.styled.ts
src/theme/theme.ts

- Added new 0.05 opacity for all colors.
- Updated background color for error wrapper around fields to use this new opcity.

Updated background color for error wrapper around fields

---

src/components/Form/Form.stories.tsx
src/components/Form/Form.tsx
src/components/LeftNav/NavWrapper.tsx
src/forms/TopComponent/TopComponent.styled.ts
src/forms/TopComponent/TopComponent.tsx
src/forms/TopComponent/Views/DesktopView.tsx

MOS-859: Form Sizing issue

---

src/components/DataView/DataViewActionsRow/DataViewActionsRow.tsx
src/components/DataView/DataViewControlDisplay/DataViewControlDisplay.styled.ts
src/components/DataView/DataViewControlDisplay/DataViewControlDisplay.tsx
src/components/DataView/DataViewControlDisplay/index.ts
src/components/DataView/DataViewLimit/DataViewControlLimit.styled.ts
src/components/DataView/DataViewLimit/DataViewControlLimit.tsx
src/components/DataView/DataViewLimit/index.ts
src/components/DataView/DataViewPager/DataViewPager.styled.ts
src/components/DataView/DataViewPager/DataViewPager.tsx
src/components/DataView/DataViewPager/DataViewPagerTypes.ts
src/components/DataView/DataViewPager/index.ts
src/theme/theme.ts

- Solves styles issues found during QA. Details found in the ticket's comments https://simpleviewtools.atlassian.net/browse/MOS-869
- Creates a directory for each component and separates the types and styles into independent files.

MOS-869: Fixes issues found by QA

---

src/components/DataView/DataViewLimit/DataViewControlLimit.styled.ts
src/components/DataView/DataViewPager/DataViewPager.styled.ts

Fix space between Pager and Control Limit

MOS-869: Fix space between Pager and Control Limit

---

src/components/Form/Form.tsx
src/forms/TopComponent/TopComponent.styled.ts
src/forms/TopComponent/TopComponent.tsx
src/forms/TopComponent/Views/MobileView.tsx
src/forms/TopComponent/Views/ResponsiveView.tsx

- Fixed references in all different types of views in TopComponent.
- Updated useRef used to define the height of the TopComponent.
- Updated height of the form to use the height of the TopComponent to use the remaining space.

Fixed scrolling issue in form with different heights

---

src/components/DataViewFilterText/DataViewFilterText.styled.ts
src/components/DataViewFilterText/DataViewFilterTextDropdownContent.tsx

Updates DV filter text to match Figma specs.

MOS-884: Update DV filter text to the newest desing

---

src/components/DataView/DataViewFilters.tsx
src/components/DataView/DataViewTitleBar/DataViewTitleBar.tsx
src/components/DataViewFilterDate/DataViewFilterDate.tsx
src/components/DataViewPrimaryFilter/DataViewPrimaryFilter.styled.ts
src/components/DataViewPrimaryFilter/DataViewPrimaryFilter.tsx
src/components/Tooltip/Tooltip.styled.tsx
src/theme/theme.ts

- Commits are self-descriptive.

Mos 868 qa fix

---

automation_testing/pages/Components/DataView/DataViewPage.ts
automation_testing/tests/Components/dataview/advanced_filters.spec.ts
automation_testing/tests/Components/dataview/columns.spec.ts
automation_testing/tests/Components/dataview/filter.spec.ts
src/components/DataView/example/DataViewKitchenSink.tsx
src/utils/JSONDB.ts

- Fixed up comparison "all" in categories_with_comparison filter

MOS-878: Categories with comparison ALL filter does not display the result correctly

---

automation_testing/pages/Components/DataView/AdvancedFiltersComponent.ts
automation_testing/pages/Components/DataView/DataViewPage.ts
automation_testing/tests/Components/dataview/advanced_filters.spec.ts
automation_testing/tests/Components/dataview/filter.spec.ts

Updated styles for DataViewFilterMultiselect
**Notes:**
Some tests fail due to "Any" being removed from the filter value. This tests have been address in the following PR: 
https://github.com/simpleviewinc/sv-mosaic/pull/303

MOS-867: Update Advanced Search filter - TAE

---

automation_testing/tests/Components/Button/button.spec.ts
src/components/Button/Button.styled.ts

#What's include?
- redHover color was replaced by darkerRed color

MOS-843: Update all references to darkerRed

---

automation_testing/pages/BasePage.ts
automation_testing/tests/Components/form/playground.spec.ts
src/forms/TopComponent/Utils/TitleWrapper.tsx

- Updated styles for the drawer title

MOS-898: Update fonts in drawer title component

---

automation_testing/pages/BasePage.ts
automation_testing/pages/Components/DataView/AdvancedFiltersComponent.ts
automation_testing/pages/Components/DataView/DataViewPage.ts
automation_testing/pages/Components/DataView/FilterComponent.ts
automation_testing/pages/Components/Form/FormWithLayoutPage.ts
automation_testing/pages/Components/SummaryPageTopComponent/SummaryPageTopComponentPage.ts
automation_testing/tests/Components/SummaryPageTopComponent/summaryPageTopComponent.spec.ts
automation_testing/tests/Components/dataview/data_view.spec.ts
automation_testing/tests/Components/dataview/filter.spec.ts
automation_testing/tests/Components/form/form_with_layout.spec.ts
src/components/DataView/DataView.tsx
src/components/DataView/DataViewFilters.tsx
src/components/DataView/DataViewTBody.tsx
src/components/DataView/DataViewTHead.tsx
src/components/DataView/DataViewTd.tsx
src/components/DataView/DataViewTitleBar/DataViewTitleBar.styled.ts
src/components/DataView/DataViewTr/DataViewTr.tsx
src/components/Form/FormLayout.tsx
src/components/Form/Section.tsx
src/components/SummaryPageTopComponent/SummaryPageTopComponent.styled.tsx
src/forms/TopComponent/TopComponent.styled.ts
src/forms/TopComponent/Views/DesktopView.tsx
src/forms/TopComponent/Views/ResponsiveView.tsx

- Updated indentation of fields

MOS-877: Update indentation of fields

---

automation_testing/pages/BasePage.ts
automation_testing/pages/Components/Form/PlaygroundPage.ts
automation_testing/tests/Components/form/playground.spec.ts
automation_testing/utils/data/knobs.ts
automation_testing/utils/formUrls.ts
src/components/Form/Col.tsx
src/components/Form/Form.stories.mdx
src/components/Form/Form.test.tsx
src/components/Form/formActions.ts
src/components/Form/formUtils.ts
src/forms/FormFieldImageVideoLinkDocumentBrowsing/ImageVideoLinkDocumentBrowsingUtils.ts
src/forms/FormFieldTable/tableUtils.ts

Adds touched property to the form's state in order to identify which field has been changed.

MOS-873: Add way to determine if a form has been modified

---

src/components/Field/Field.tsx
src/components/Field/FieldTypes.tsx
src/components/Form/Col.tsx
src/components/Form/formActions.ts

Scrolls to the first invalid field at the moment of submitting a form.

MOS-888: Scrolling to the nearest invalid field

---

src/components/DataView/DataViewDisplayList.tsx

- Updated data prop of the DataViewTHead component

MOS-906: Display list header getting the wrong data

---

src/components/Button/Button.styled.ts
src/components/Card/Card.stories.tsx
src/components/Content/Content.styled.ts
src/components/DataView/DataViewBulkAllBar.tsx
src/components/DataView/DataViewTHead.tsx
src/components/DataViewPrimaryFilter/DataViewPrimaryFilter.styled.ts
src/components/Field/HelperText.styled.ts
src/components/Field/InstructionText.styled.ts
src/components/Field/Label.tsx
src/components/HelperText/HelperText.styled.ts
src/components/IconButton/IconButton.styled.tsx
src/components/InstructionText/InstructionText.styled.ts
src/components/LeftNav/LeftNavDesktop.tsx
src/components/LeftNav/LeftNavMobile.tsx
src/components/Popover/Popover.stories.tsx
src/components/SideNav/SideNav.styled.tsx
src/forms/FormFieldAdvancedSelection/AdvancedSelection.styled.tsx
src/forms/FormFieldCheckbox/FormFieldCheckbox.styled.ts
src/forms/FormFieldDate/DatePicker/DatePicker.styled.tsx
src/forms/FormFieldDropdownSingleSelection/FormFieldDropdownSingleSelection.styled.tsx
src/forms/FormFieldImageUpload/FormFieldImageUpload.styled.ts
src/forms/FormFieldImageVideoLinkDocumentBrowsing/ImageVideoLinkDocumentBrowsing.styled.tsx
src/forms/FormFieldMapCoordinates/MapCoordinates.styled.tsx
src/forms/FormFieldPhoneSelectionDropdown/FormFieldPhoneSelectionDropdown.styled.tsx
src/forms/FormFieldTextArea/FormFieldTextArea.styled.tsx
src/forms/FormNav/FormNav.styled.tsx
src/forms/TopComponent/Utils/TitleWrapper.tsx
src/theme/theme.ts

Update references to gray3
The new color grey3 was equal to gray600, gray and assistiveText colors.

MOS-846: Update all references to gray3

---

src/components/Card/Card.stories.tsx
src/components/Checkbox/Checkbox.styled.ts
src/components/Content/Content.styled.ts
src/components/LeftNav/LeftNavGroup.tsx
src/components/LeftNav/LeftNavMobile.tsx
src/components/MenuItem/MenuItem.tsx
src/components/Popover/Popover.stories.tsx
src/components/SideNav/SideNav.styled.tsx
src/components/StyledFormControlLabel/StyledFormControl.styled.tsx
src/forms/FormFieldCheckbox/FormFieldCheckbox.styled.ts
src/forms/FormFieldDate/DatePicker/DatePicker.styled.tsx
src/forms/FormFieldDropdownSingleSelection/FormFieldDropdownSingleSelection.styled.tsx
src/forms/MenuFormFieldCard/MenuFormFieldCard.styled.tsx

- Updated all references to gray4

MOS-847: Update all references to gray4

---

src/components/DataView/DataViewTitleBar/DataViewTitleBarTypes.ts
src/components/DataView/DataViewTypes.ts

- Updated savedViewState keys as not required

MOS-907: Mosaic saved view def has required keys that don't make sense

---

src/components/Button/Button.styled.ts
src/components/Button/Button.tsx

Updates Buttons component to close the tooltip when clicking away.

MOS-452: Tooltip on buttons is hide when clicking away

---

src/components/DataView/DataView.tsx
src/components/DataView/DataViewTypes.ts
src/components/DataView/DataViewViewDrawerContent.tsx
src/components/DrawerContent/DrawerContent.tsx

MOS-901: Browse saved views has bad spacing

---

automation_testing/pages/BasePage.ts
automation_testing/pages/Components/Form/PlaygroundPage.ts
automation_testing/pages/Components/SnackBar/SnackBarPagePage.ts
automation_testing/pages/Components/ToggleSwitch/ToggleSwitchPage.ts
automation_testing/pages/FormFields/FormFieldPhoneSelectionDropdownPage.ts
automation_testing/tests/Components/SnackBar/snackbar.spec.ts
automation_testing/tests/Components/ToggleSwitch/toggleSwitch.spec.ts
automation_testing/tests/Components/form/playground.spec.ts
automation_testing/tests/FormFields/formFieldAdvancedSelection.spec.ts
automation_testing/tests/FormFields/formFieldPhoneSelectionDropdown.spec.ts
automation_testing/utils/data/knobs.ts

https://simpleviewtools.atlassian.net/browse/MOS-848
The PR objective is to update all files / components / fields that should be using the simplyGray but are currently using a similar color but with different name.

TAE - MOS-848 - Update all references to simplyGray

---

automation_testing/pages/BasePage.ts
automation_testing/pages/Components/Card/CardPage.ts
automation_testing/pages/Components/Popover/PopoverTextAndLinksPage.ts
automation_testing/pages/Components/leftNav/LeftNavPage.ts
automation_testing/tests/Components/Card/card.spec.ts
automation_testing/tests/Components/MenuItem/menuItem.spec.ts
automation_testing/tests/Components/Popover/popoverTextAndLink.spec.ts
automation_testing/tests/Components/leftNav/left_nav.spec.ts
automation_testing/tests/FormFields/formFieldCheckbox.spec.ts

https://simpleviewtools.atlassian.net/browse/MOS-847
The PR objective is to update all files / components / fields that should be using the gray4 but are currently using a similar color but with different name.

TAE - MOS-847 - Update all references to gray4

---

automation_testing/pages/Components/DataView/PaginationComponent.ts
automation_testing/pages/Components/DataView/SaveAsComponent.ts
automation_testing/tests/Components/dataview/advanced_filters.spec.ts
automation_testing/tests/Components/dataview/save_as.spec.ts

https://simpleviewtools.atlassian.net/browse/MOS-906
Regression of Bulk actions in dataview. It's also included fixed for various dataview tests.

TAE - MOS-906 - Display list header getting the wrong data

---

automation_testing/pages/Components/DataView/SaveAsComponent.ts
automation_testing/tests/Components/dataview/save_as.spec.ts

https://simpleviewtools.atlassian.net/browse/MOS-901
Added tests validating the color of buttons and text of the saved views drawer.

TAE - MOS-901 - Browse saved views has bad spacing

---

automation_testing/pages/Components/Content/ContentPage.ts
automation_testing/pages/Components/Popover/PopoverTextAndLinksPage.ts
automation_testing/pages/Components/leftNav/LeftNavPage.ts
automation_testing/pages/FormFields/FormFieldAdvancedSelectionPage/AdvancedSelectionKitchenSinkPage.ts
automation_testing/pages/FormFields/FormFieldAdvancedSelectionPage/AdvancedSelectionPlaygroundPage.ts
automation_testing/pages/FormFields/FormFieldCheckboxPage.ts
automation_testing/tests/Components/Button/button.spec.ts
automation_testing/tests/Components/Card/card.spec.ts
automation_testing/tests/Components/Content/content.spec.ts
automation_testing/tests/Components/Popover/popoverTextAndLink.spec.ts
automation_testing/tests/Components/leftNav/left_nav.spec.ts
automation_testing/tests/FormFields/formFieldAdvancedSelectionKitchenSink.spec.ts
automation_testing/tests/FormFields/formFieldAdvancedSelectionPlayground.spec.ts
automation_testing/tests/FormFields/formFieldCheckbox.spec.ts
automation_testing/tests/FormFields/formFieldDropdownSingleSelection.spec.ts

https://simpleviewtools.atlassian.net/browse/MOS-846
The PR objective is to update all files / components / fields that should be using the gray3 but are currently using a similar color but with different name.

TAE - MOS-846 - Update all references to gray3

---

automation_testing/tests/Components/dataview/advanced_filters.spec.ts

https://simpleviewtools.atlassian.net/browse/MOS-452
Added scenario for where an empty filter shouldn't trigger a reload if removed.

TAE - MOS-67 - Triggered Reload

---

automation_testing/pages/BasePage.ts
automation_testing/pages/Components/DataView/DataViewFilterDateComponent.ts
automation_testing/tests/Components/dataview/DataViewFilterDate.spec.ts
automation_testing/utils/data/knobs.ts

https://simpleviewtools.atlassian.net/browse/MOS-902
The PR objective is to add a scenario that contemplates the new pre-filled magic values to the date filter.

TAE - MOS-902 - Add pre-filled magic values to the date filter

---

automation_testing/pages/FormFields/FormFieldMatrixPage/FormFieldMatrixBrowsePage.ts
automation_testing/pages/FormFields/FormFieldMatrixPage/FormFieldMatrixFormVariantPage.ts
automation_testing/tests/FormFields/formFieldMatrixBrowse.spec.ts
automation_testing/tests/FormFields/formFieldMatrixFormVariant.spec.ts

Jira Ticket
https://simpleviewtools.atlassian.net/browse/MOS-809
What's included?
The PR objective is to add scenarios for the new FormFieldMatrix in its two variants: Browse and Form.

TAE - MOS-809 - Create Matrix Field

---

.storybook/main.js
package.json

- Added "StorySource" addon. This shows the code used to create each story and will hopefully help other devs understand a bit better how to use each component.

MOS-909 Added storysource addon to see source code for all stories

---

automation_testing/pages/BasePage.ts
automation_testing/pages/Components/Checkbox/CheckboxPage.ts
automation_testing/pages/Components/DataView/AdvancedFiltersComponent.ts
automation_testing/pages/Components/DataView/DataViewFilterMultiselect.ts
automation_testing/pages/Components/DataView/DataViewPage.ts
automation_testing/pages/Components/DataView/FilterComponent.ts
automation_testing/pages/Components/ToggleSwitch/ToggleSwitchPage.ts
automation_testing/pages/FormFields/FormFieldToggleSwitchPage.ts
automation_testing/tests/Components/ToggleSwitch/toggleSwitch.spec.ts
automation_testing/tests/Components/dataview/DataViewFilterMultiselect.spec.ts
src/components/DataView/DataViewFilters.tsx
src/components/DataViewFilterMultiselect/DataViewFilterMultiselect.stories.mdx
src/components/DataViewFilterMultiselect/DataViewFilterMultiselect.stories.tsx
src/components/DataViewFilterMultiselect/DataViewFilterMultiselect.tsx

- Added story and knobs to DataViewFilterMultiSelect component.
- Added documentation to DataViewFilterMultiSelect component.

MOS-917: Create story and documentation for DataViewFilterMultiSelect

---

src/components/DataViewFilterMultiselect/DataViewFilterMultiselect.stories.tsx

- Removed comparisonDefault knob from storybook

MOS-917: Hotfix - Create story and documentation for DataViewFilterMultiSelect

---

automation_testing/pages/BasePage.ts
automation_testing/tests/Components/dataview/filter.spec.ts
src/components/DataView/DataView.tsx

Adds margin to the "No results" message to be aligned to the Data View table.

MOS-941: No results message misaligned

---

automation_testing/pages/Components/DataView/AdvancedFiltersComponent.ts
automation_testing/tests/Components/dataview/advanced_filters.spec.ts
src/components/DataViewFilterDate/DataViewFilterDateDropdownContent.tsx
src/components/Field/Field.tsx
src/components/Field/FieldTypes.tsx
src/components/Field/HelperText.styled.ts
src/components/Field/HelperText.tsx
src/forms/FormFieldChipSingleSelect/FormFieldChipSingleSelect.tsx
src/forms/FormFieldText/FormFieldText.tsx
src/forms/FormFieldTextArea/FormFieldTextArea.tsx

- Updated DVFilterDate component to use mosaic's field styles

Mos-944: Update DVFilterDate to use mosaic's field styles

---

src/components/Form/Form.stories.tsx
src/components/Form/Form.tsx
src/components/Form/FormLayout.tsx
src/components/Form/Section.tsx
src/forms/FormNav/FormNav.tsx
src/forms/TopComponent/TopComponent.tsx
src/forms/TopComponent/Views/DesktopView.tsx

Fixes the issue of section highlights when making a change on a form field caused by a re-render of the Sections component.

MOS-903: Sections are not highlighted correctly

---

automation_testing/tests/Components/dataview/filter.spec.ts
src/components/DataView/DataViewFilters.tsx

- Added condition to DVFilters when it should be cleared

MOS-953: Clearing filter doesn't clear the filter

---

automation_testing/pages/FormFields/FormFieldUploadPage.ts
automation_testing/tests/FormFields/formFieldUpload.spec.ts
src/forms/FormFieldUpload/FormFieldUpload.stories.tsx
src/forms/FormFieldUpload/FormFieldUpload.tsx

- Disables upload button based on loaded and pending files.
- Adds a knob to set the seconds that each file will take to load completely.

MOS-961: Updated to upload component

---

automation_testing/pages/BasePage.ts
automation_testing/pages/Components/Drawers/DrawersPage.ts
automation_testing/pages/FormFields/FormFieldMatrixPage/FormFieldMatrixFormVariantPage.ts
automation_testing/tests/Components/drawers/drawers.spec.ts

https://simpleviewtools.atlassian.net/browse/MOS-971
At the moment, the tests for the Drawer component are outdated. We need to check and update the tests to represent the present behavior.

TAE - MOS-971 - Update tests for Drawers component

---

src/components/Form/Form.styled.ts
src/components/Form/Form.tsx

- Updated disabled form styles

MOS-962: The form disable mechanic is too distracting

---

src/components/Field/FieldTypes.tsx
src/components/Form/Col.tsx
src/components/Form/Form.stories.mdx
src/components/Form/Form.stories.tsx
src/forms/FormFieldNumberTable/FormFieldNumberTable.stories.mdx
src/forms/FormFieldNumberTable/FormFieldNumberTable.stories.tsx
src/forms/FormFieldNumberTable/FormFieldNumberTable.styled.tsx
src/forms/FormFieldNumberTable/FormFieldNumberTable.test.tsx
src/forms/FormFieldNumberTable/FormFieldNumberTable.tsx
src/forms/FormFieldNumberTable/FormFieldNumberTableTypes.ts
src/forms/FormFieldNumberTable/index.ts
src/forms/FormFieldNumberTable/numberTableUtils.ts

- Implementation of FormFieldTable based on this Figma file: https://www.figma.com/file/uHwrWEXr6pvYPI66BGHwzn/Lead_DMS?node-id=1500%3A47277&t=p1jS4r6RkRdCqPMP-0
- Respective playground story added
- Documentation included
- Unit tests

MOS-970: Form field number table

---

automation_testing/tests/Components/drawers/drawers.spec.ts
src/components/Button/Button.styled.ts
src/components/Button/Button.tsx
src/components/Drawers/example/FormExample.tsx

- Updated the button tooltip to utilize z-index: 1500

MOS-963: Tooltip z-index is incorrect

---

src/components/Card/Card.stories.tsx
src/components/Card/Card.styled.tsx
src/components/Card/Card.test.tsx
src/components/Card/Card.tsx
src/components/Card/CardTypes.ts

- titleIcon Card's prop change from JSX.Element to SvgIconComponent

MOS-969: Icon Card type updated 1

---

.storybook/preview-body.html
automation_testing/pages/BasePage.ts
automation_testing/pages/Components/Drawers/DrawersPage.ts
automation_testing/pages/Components/Form/PlaygroundPage.ts
automation_testing/tests/Components/SummaryPageTopComponent/summaryPageTopComponent.spec.ts
automation_testing/tests/Components/dataview/advanced_filters.spec.ts
automation_testing/tests/Components/dataview/data_view.spec.ts
automation_testing/tests/Components/drawers/drawers.spec.ts
automation_testing/tests/Components/form/playground.spec.ts
src/components/DataView/DataViewTitleBar/DataViewTitleBar.styled.ts
src/components/DataView/DataViewTitleBar/DataViewTitleBar.tsx
src/components/DrawerHeader/DrawerHeader.tsx
src/components/Form/Section.tsx
src/components/SummaryPageTopComponent/SummaryPageTopComponent.styled.tsx
src/components/SummaryPageTopComponent/SummaryPageTopComponent.tsx
src/components/Typography/H1.tsx
src/forms/TopComponent/Utils/TitleWrapper.tsx
src/forms/TopComponent/Views/DesktopView.tsx
src/forms/TopComponent/Views/DrawerView.tsx
src/forms/TopComponent/Views/MobileView.tsx
src/forms/TopComponent/Views/ResponsiveView.tsx
src/forms/TopComponent/Views/Views.styled.ts
src/theme/theme.ts

- Updated H1 component styles
- Creation of TitleWrapper component that internally renders an H1
- TitlteWrapper component replaced previously used styled Title on Forms, DrawerHeader, SummaryPageTopComponent, and DV

MOS-964: Update h1 to be consistent

---

src/components/Form/Section.tsx

MOS-964: Fix sections titles styles

---

automation_testing/pages/BasePage.ts
automation_testing/pages/FormFields/FormFieldNumberTablePage.ts
automation_testing/tests/FormFields/formFieldNumberTable.spec.ts

https://simpleviewtools.atlassian.net/browse/MOS-970
Added automation tests for Form Field Number Table.

TAE - MOS-970 - Implement NumberTable

---

automation_testing/pages/FormFields/FormFieldAddressPage.ts
automation_testing/tests/FormFields/formFieldAddress.spec.ts
src/components/DrawerHeader/DrawerHeader.tsx
src/forms/FormFieldAddress/AddressDrawer/AddressDrawer.tsx
src/forms/FormFieldAdvancedSelection/AdvancedSelection.test.tsx
src/forms/TopComponent/Views/DrawerView.tsx

- Fixes address state label misspelling.

MOS-974: Address field state label mispelling

---

src/components/Card/Card.test.tsx
src/components/Card/Card.tsx

- Renders conditionally titleIcon on Card component

MOS-969: Fix title icon on Card when is not passed as prop

---

src/forms/FormFieldNumberTable/FormFieldNumberTable.styled.tsx
src/forms/FormFieldNumberTable/FormFieldNumberTable.tsx

- Updated colors from all texts in the table to use almostBlack
- Updated onChange logic so value (and rows) gets completely deleted when no cells have value (this will trigger an error message if required is true).

Mos 970 logic fix

---

automation_testing/tests/Components/Chip/chip.spec.ts
src/components/Chip/Chip.styled.ts

Updates chips styles when hovering over it.

MOS-985: Update styling of chips when hovering

---

src/forms/shared/styledComponents.ts

Makes the advanced selection drawer wider.

MOS-988: Make advanced selection Drawer wider

---

automation_testing/pages/BasePage.ts
automation_testing/pages/Components/DataView/DataViewPage.ts
automation_testing/tests/Components/dataview/data_view.spec.ts
src/components/DataView/DataView.tsx
src/components/DataView/DataViewTBody.tsx
src/components/DataView/DataViewTHead.tsx

Updates DV dimensions according to design call.

MOS-984: Update DV dimensions

---

automation_testing/pages/BasePage.ts
automation_testing/pages/FormFields/FormFieldUploadPage.ts
automation_testing/tests/FormFields/formFieldUpload.spec.ts
src/forms/shared/styledComponents.ts

- Added z-index to the "upload file" button

MOS-986: "Upload File" button not showing hover state

---

automation_testing/pages/BasePage.ts
automation_testing/pages/Components/DataView/SaveAsComponent.ts
automation_testing/pages/Components/SummaryPageTopComponent/SummaryPageTopComponentPage.ts
automation_testing/pages/FormFields/FormFieldImageVideoLinkDocumentBrowsingPage.ts
automation_testing/tests/Components/SummaryPageTopComponent/summaryPageTopComponent.spec.ts
src/components/Button/Button.styled.ts
src/components/SummaryPageTopComponent/SummaryPageTopComponent.styled.tsx
src/components/SummaryPageTopComponent/SummaryPageTopComponent.test.tsx
src/components/SummaryPageTopComponent/SummaryPageTopComponent.tsx

Changes the favorite icon to a Button with a variant icon.

MOS-978: SummaryTopComponent onClick not showing proper hover state

---

automation_testing/tests/FormFields/formFieldPhoneSelectionDropdown.spec.ts
src/forms/FormFieldPhoneSelectionDropdown/FormFieldPhoneSelectionDropdown.tsx

Fixes phone dropdown field to save undefined in the Form value when the only number in the field is the dial code.

MOS-992: Phone field retuns invalid data

---

automation_testing/tests/FormFields/formFieldAddress.spec.ts
src/forms/FormFieldAddress/AddressDrawer/AddressDrawer.tsx
src/forms/FormFieldAddress/utils/addressUtils.ts

- Added street_number to address field

MOS-981: Address field is losing the typed in number

---

automation_testing/pages/BasePage.ts
automation_testing/pages/Components/DataView/ColumnsComponent.ts
automation_testing/pages/Components/DataView/FilterComponent.ts
automation_testing/pages/Components/Drawers/DrawersPage.ts
automation_testing/tests/Components/dataview/columns.spec.ts
automation_testing/tests/FormFields/formFieldAdvancedSelectionPlayground.spec.ts
src/components/Chip/Chip.tsx

- Added a tooltip to the deletable chip component when its width exceeds 186px.

MOS-987: Add tooltips to Chips

---

automation_testing/pages/Components/Form/FormWithLayoutPage.ts
src/components/Form/Form.tsx
src/forms/TopComponent/TopComponent.styled.ts

Replaces the form content height computation with flexbox.

MOS-890: Scrollbar simplification

---

automation_testing/tests/Components/dataview/columns.spec.ts
src/components/DataView/DataViewColumDrawer/DataViewColumnDrawerContent.tsx
src/components/Drawers/example/FormExample.tsx
src/components/Drawers/example/Grid.tsx
src/forms/FormFieldAddress/AddressDrawer/AddressDrawer.tsx
src/forms/FormFieldAdvancedSelection/AdvancedSelectionDrawer.tsx
src/forms/FormFieldMapCoordinates/MapCoordinatesDrawer/MapCoordinatesDrawer.tsx
src/forms/FormFieldMatrix/FormFieldMatrix.stories.tsx

Adds onBack prop to the following components.
- AdvancedSelection
- Address
- MapCoordinates
- Matrix stories
- Drawers stories
- DataView in the columns drawer

MOS-990: Adds onBack to form fields

---

automation_testing/tests/Components/Button/buttonPlayground.spec.ts
automation_testing/tests/Components/SummaryPageTopComponent/summaryPageTopComponent.spec.ts
src/components/Button/Button.stories.tsx
src/components/Button/Button.styled.ts
src/components/SummaryPageTopComponent/SummaryPageTopComponent.styled.tsx
src/components/SummaryPageTopComponent/SummaryPageTopComponent.tsx

- Adds simply gold color to the icon buttons variants.

MOS-995: Adds simply gold color to buttons icon variant

---

automation_testing/pages/Components/DataView/DataViewFilterDateComponent.ts
automation_testing/tests/Components/dataview/DataViewFilterDate.spec.ts
src/components/DataViewFilterDate/DataViewFilterDate.stories.mdx
src/components/DataViewFilterDate/DataViewFilterDate.stories.tsx

- Added Readme to component.
- Renamed "Example" story to "Playground".
- Added KitchenSink with variants of the component.

Mos 1000 DataViewFilterDate missing Readme

---

automation_testing/pages/BasePage.ts
automation_testing/pages/Components/DataView/DataViewFilterText.ts
automation_testing/pages/Components/DataView/DataViewPage.ts
automation_testing/pages/FormFields/FormFieldTextPage.ts
automation_testing/tests/Components/dataview/DataViewFilterText.spec.ts
automation_testing/tests/Components/dataview/advanced_filters.spec.ts
automation_testing/tests/Components/dataview/filter.spec.ts
automation_testing/tests/Components/form/validators.spec.ts
automation_testing/tests/FormFields/formFieldAddress.spec.ts
automation_testing/tests/FormFields/formFieldImageVideoLinkDocumentBrowsing.spec.ts
automation_testing/utils/data/knobs.ts
src/components/DataViewFilterText/DataViewFilterText.stories.mdx
src/components/DataViewFilterText/DataViewFilterText.stories.tsx

- Created Readme for component.
- Created Playground and Kitchensink stories.

MOS-1002 Create story for DataViewFilterText

---

automation_testing/pages/Components/PageHeader/PageHeaderPage.ts
automation_testing/tests/Components/PageHeader/pageHeader.spec.ts
automation_testing/utils/data/knobs.ts
src/components/PageHeader/PageHeader.stories.mdx
src/components/PageHeader/PageHeader.stories.tsx
src/utils/storyUtils.ts

- Created ReadMe for component.
- Created Playground.
- Now exporting "onCancel" from "storyUtils" to reuse in PageHeader story.

MOS-1004 Create story for PageHeader

---

src/components/Spinner/Spinner.stories.mdx
src/components/Spinner/Spinner.stories.tsx
src/components/Spinner/Spinner.test.tsx
src/components/Spinner/Spinner.tsx
src/forms/FormFieldText/FormFieldText.test.tsx

- Created Readme.
- Created Playground and KitchenSink.
- Created unit tests.
- Improved progress condition
- Updated name from FormFieldText's test

MOS-1003 Create story for Spinner component

---

src/components/Button/Button.styled.ts

Removes rounded borders for all buttons.

MOS-996: Buttons showing round borders when clicked

---

automation_testing/pages/Components/DataView/DataViewPage.ts
automation_testing/tests/Components/dataview/columns.spec.ts
automation_testing/tests/Components/dataview/data_view.spec.ts
src/components/DataView/DataView.stories.tsx
src/components/DataView/DataViewTBody.tsx
src/components/DataView/DataViewTd.tsx

MOS-1007: Bold styling on DV columns not working

---

automation_testing/pages/FormFields/FormFieldUploadPage.ts
automation_testing/tests/FormFields/formFieldUpload.spec.ts
automation_testing/utils/data/knobs.ts
src/components/Form/Col.tsx
src/forms/FormFieldText/FormFieldText.stories.tsx
src/forms/FormFieldTextEditor/FormFieldTextEditor.test.tsx
src/forms/FormFieldUpload/FileCard/FileCard.tsx
src/forms/FormFieldUpload/FileCard/FileCardTypes.ts
src/forms/FormFieldUpload/FormFieldUpload.tsx

Updates the disabled state of the Upload field

MOS-1012: Update disabled state for file upload field

---

src/components/DataView/DataViewActionsButtonRow.tsx

Changes the MoreHorizontal icon on DV with list display to be the MoreVertical icon.

MOS-1026: Update the icon of the additional actions on DV

---

automation_testing/pages/Components/SummaryPageTopComponent/SummaryPageTopComponentPage.ts
automation_testing/tests/Components/SummaryPageTopComponent/summaryPageTopComponent.spec.ts
automation_testing/utils/data/knobs.ts
src/components/SummaryPageTopComponent/SummaryPageTopComponent.stories.tsx
src/components/SummaryPageTopComponent/SummaryPageTopComponent.test.tsx
src/components/SummaryPageTopComponent/SummaryPageTopComponent.tsx

- SummaryTopComponent  no longer renders  the menu that contains the additional action if an empty array is passed
- Adds select knob to enable automation and visual testing
- Adds a unit test that covers this case

MOS-1037: SummaryTopComponent shows additional actions even if the array is empty

---

src/components/DataViewFilterMultiselect/DataViewFilterMultiselectDropdownContent.tsx
src/components/DataViewFilterText/DataViewFilterTextDropdownContent.tsx

- Disabled autocomplete on keyword filters and categories

MOS-1008: Disabled autocomplete on filters keyword

---

.eslintrc.json
automation_testing/tests/FormFields/formFieldText.spec.ts
src/forms/FormFieldText/FormFieldText.styled.tsx

- Cleaned code in FormFieldText.styled.tsx to align heights between the regular and multiline variants.

MOS-1022 Validate correct height between regular and multiline text fields

---

automation_testing/tests/FormFields/FormFieldNumberTable/FormFieldNumberTable.spec.ts
src/forms/FormFieldNumberTable/FormFieldNumberTable.tsx

Increases the NumberTable's inputs width from 72px to 90px.

MOS-1042: Increase size of the NumberTable's inputs

---

automation_testing/pages/FormFields/FormFieldNumberTable/FormFieldNumberTablePage.ts
automation_testing/tests/FormFields/FormFieldNumberTable/FormFieldNumberTable.spec.ts
automation_testing/utils/data/knobs.ts
src/components/Form/Form.stories.mdx
src/forms/FormFieldNumberTable/FormFieldNumberTable.stories.tsx
src/forms/FormFieldNumberTable/FormFieldNumberTable.test.tsx
src/forms/FormFieldNumberTable/FormFieldNumberTable.tsx
src/forms/FormFieldNumberTable/FormFieldNumberTableTypes.ts

Implements support for intl.Number format options in the NumberTable component.

MOS-1040: Update NumberTable to support intl.Number format options

---

automation_testing/pages/Components/DataView/DataViewFilterText.ts
automation_testing/tests/Components/dataview/DataViewFilterText.spec.ts
automation_testing/utils/data/knobs.ts
src/components/DataViewFilterText/DataViewFilterText.styled.ts
src/components/DataViewFilterText/DataViewFilterText.tsx
src/components/DataViewFilterText/DataViewFilterTextDropdownContent.tsx

Fixes filter get default comparison logic.

MOS-1045: Text filter comparison logic incosistent

---

automation_testing/tests/Components/SummaryPageTopComponent/SummaryPageTopComponent.spec.ts
src/components/SummaryPageTopComponent/SummaryPageTopComponent.stories.tsx
src/components/SummaryPageTopComponent/SummaryPageTopComponent.test.tsx
src/components/SummaryPageTopComponent/SummaryPageTopComponent.tsx

- Updated SummaryPageTopComponent's playground story to include "undefined" as a value for additional actions.
- Updated unit tests to account for undefined scenario and updated tests previously in ToDo.
- Added conditional that throwed an error when no additional actions get passed.

MOS-1060 MOSAIC BUG for version 22 - Undefined Additional Actions in SummaryPageTopComponent causes TypeError

---

automation_testing/pages/BasePage.ts
automation_testing/tests/FormFields/FormFieldNumberTable/FormFieldNumberTable.spec.ts
src/forms/FormFieldNumberTable/FormFieldNumberTable.tsx

- Added function that allows users to move between cells using arrow keys

MOS-1050 Update NumberTable to allow arrow key navigation

---

automation_testing/pages/Components/DataView/DataViewPage.ts
automation_testing/tests/Components/dataview/AdvancedFilters.spec.ts
automation_testing/tests/Components/dataview/Columns.spec.ts
automation_testing/tests/Components/dataview/Filter.spec.ts
automation_testing/tests/Components/dataview/SaveAs.spec.ts
src/components/DataView/DataViewTd/DataViewTd.tsx
src/components/DataView/DataViewTd/DataViewTdTypes.ts
src/components/DataView/DataViewTr/DataViewTr.tsx

- Modified DataViewTd's types to accept aria-labels
- Updated DataViewTr to pass aria-label to Td's
- Updated DataViewTd to use aria-labels

MOS-1057 Add data-testid to Grid columns

---

automation_testing/tests/FormFields/FormFieldNumberTable/FormFieldNumberTable.spec.ts
src/forms/FormFieldNumberTable/FormFieldNumberTable.stories.tsx
src/forms/FormFieldNumberTable/FormFieldNumberTable.tsx

- Added "prepopulate" knob to Playground to ease testing scenario.
- Added conditional to formatting function to prevent a total to be calculated if no value is present.

MOS-1068 FormFieldNumberTable renders NaN when table is empty but has format

---

automation_testing/pages/FormFields/FormFieldNumberTable/FormFieldNumberTablePage.ts
automation_testing/tests/FormFields/FormFieldNumberTable/FormFieldNumberTable.spec.ts
src/forms/FormFieldNumberTable/FormFieldNumberTable.stories.tsx

- Updated format options knob to use json rather than dropdown, this allows users to pass whatever format they'd like to use.

MOS-1063 FormFieldNumberTable : display issues with JPY format & no format

---

src/forms/FormFieldNumberTable/FormFieldNumberTable.tsx

- Updated formatting function to always format as long as the column has a value.

MOS-1070 Update numberFormatOptions in FormFieldNumberTable to allow default formatting

---

src/components/PageHeader/PageHeader.styled.tsx
src/components/PageHeader/PageHeader.tsx
src/theme/theme.ts

- Updated max-widths in PageHeader component to make the title collapse when it reaches a certain width.

MOS-1048 Fixed width issues with PageHeader component

---

src/components/Blank/Blank.tsx
src/components/Blank/BlankTypes.ts
src/components/Blank/index.ts
src/components/Content/Content.stories.tsx
src/components/Content/Content.tsx
src/components/Form/Col.tsx

This PR introduces a new "Blank" component. This component will be used across all components designed to display a value that can be undefined, an empty string, or any other value considered "empty". It is being consumed by the Field Col and Content components.

MOS-1086 Introduced and implemented a generic Blank component

---

src/components/Form/Form.stories.tsx
src/forms/FormFieldText/FormFieldText.styled.tsx

This PR removes the padding, line height and height styling from the FormFieldText

MOS-1089 textfield height

---

src/components/Field/RegisteredField.tsx
src/components/Form/Col.tsx
src/components/Form/Form.stories.mdx
src/components/Form/Form.stories.tsx
src/components/Form/Form.tsx
src/components/Form/FormLayout.tsx
src/components/Form/FormTypes.tsx
src/components/Form/Section.tsx
src/components/Form/formActions.ts
src/components/Form/formUtils.ts

This PR is a follow on from https://github.com/simpleviewinc/sv-mosaic/pull/463 and brings the _show_ behaviour to form sections as well as fields.

MOS-1056 Add show behaviour to sections

---

src/components/ButtonRow/ButtonRow.styled.tsx
src/components/ButtonRow/ButtonRow.tsx
src/components/ButtonRow/ButtonRowTypes.ts
src/components/Card/Card.stories.tsx
src/components/Card/Card.styled.tsx
src/components/Card/Card.tsx
src/components/Content/Content.stories.tsx
src/components/Content/Content.styled.ts
src/components/Content/Content.tsx
src/components/DataView/DataViewActionsButtonRow/DataViewActionsButtonRow.tsx
src/components/DataView/DataViewActionsRow/DataViewActionsRow.styled.ts
src/components/DataView/DataViewActionsRow/DataViewActionsRow.tsx
src/components/DataView/DataViewControlDisplay/DataViewControlDisplay.styled.ts
src/components/DataView/DataViewDisplayGridSortControl/DataViewDisplayGridSortControl.tsx
src/components/DataView/DataViewLimit/DataViewControlLimit.styled.ts
src/components/DataView/DataViewTitleBar/DataViewTitleBar.tsx
src/components/PageHeader/PageHeader.tsx
src/components/SummaryPageTopComponent/SummaryPageTopComponent.styled.tsx
src/components/SummaryPageTopComponent/SummaryPageTopComponent.tsx
src/forms/TopComponent/Views/DesktopView.tsx
src/forms/TopComponent/Views/MobileView.tsx

This PR slightly modifies the ButtonRow component to allow it to be used across more components where a list of buttons is possible, improving consistency. It adds support for button separators - in this case a simple grey pipe - to make it diverse enough to reuse where the context calls for it.

MOS-1090 ButtonRow modifications and usage

---

src/components/Form/formActions.ts

This PR introduces a small change that prevents unwanted data from being submitted by filtering out any values for fields that are not mounted.

MOS-1123 Filters out data from unmounted fields

---

src/components/Form/Form.tsx
src/components/Form/FormTypes.tsx

This PR Gives form spy a default threshold and provides a way to configure it

MOS-975 Gives form spy a default threshold and provides a way to configure it

---

src/components/LeftNav/LeftNavDesktop.tsx
src/components/LeftNav/LeftNavMobile.tsx
src/components/LeftNav/LeftNavRoot.tsx

This PR amends the `LeftNav` container to implement a HTML5 `nav` element rather than a `div` as well as applying an `aria-label` attribute with a value of `Main`.

MOS-1062 Updates nav containers to use HTML5 tags and aria-label

---

src/components/ButtonRow/ButtonRow.styled.tsx
src/components/ButtonRow/ButtonRow.tsx

This PR swaps out a prop for a transient version on the `ButtonRow` styled component

MOS-1142 Use transient prop for ButtonRow styled component

---

src/components/Form/stories/FormWithLayout.stories.tsx
src/forms/FormFieldText/FormFieldText.styled.tsx

This PR addresses the styling - specifically the padding and line height - of textfield components to bring the aesthetic more in line with what is shown in the Figma document.

MOS-1099 textfield padding

---

src/forms/FormFieldText/FormFieldText.styled.tsx

Further fixes for the `FormFieldText` padding issues.

MOS-1099 Updates FormFieldText styles to fix padding

---

src/components/Form/formActions.ts
src/components/Form/validators.ts
src/forms/FormFieldPhoneSelectionDropdown/FormFieldPhoneSelectionDropdown.tsx

Reverts simpleviewinc/sv-mosaic#499

Revert "MOS-1124 Adds a phone field validation check for US numbers"

---

automation_testing/tests/FormFields/FormFieldMapCoordinates/FormFieldMapCoordinates.spec.ts
src/forms/FormFieldMapCoordinates/FormFieldMapCoordinates.tsx
src/forms/FormFieldMapCoordinates/Map/Map.tsx
src/forms/FormFieldMapCoordinates/Map/MapWithMarker.tsx
src/forms/FormFieldMapCoordinates/MapCoordinates.stories.tsx
src/forms/FormFieldMapCoordinates/MapCoordinates.styled.tsx
src/forms/FormFieldMapCoordinates/MapCoordinates.test.tsx
src/forms/FormFieldMapCoordinates/MapCoordinatesDrawer/MapCoordinatesDrawer.tsx
src/forms/FormFieldMapCoordinates/MapCoordinatesTypes.ts

This PR introduces a breaking change that removes the address to coordinates functionality from the `FormFieldMapCoordinates` field.

MOS-1041 Drops FormFieldMapCoordinates address to coords function

---

src/forms/FormFieldAddress/Address.test.tsx
src/forms/FormFieldAddress/FormFieldAddress.tsx

Adds a removal confirmation dialog to `FormFieldAddress` field

MOS-1101 Add removal confirmation dialog to FormFieldAddress

---

src/forms/FormFieldMapCoordinates/FormFieldMapCoordinates.tsx

Adds a removal confirmation dialog to `FormFieldMapCoordinates` field.

MOS-1102 Add removal confirmation dialog to FormFieldMapCoordinates

---

automation_testing/tests/Components/Chip/chip.spec.ts
automation_testing/tests/FormFields/FormFieldAdvancedSelection/FormFieldAdvancedSelectionPlayground.spec.ts
src/components/Chip/Chip.stories.tsx
src/components/Chip/Chip.styled.ts
src/components/Chip/Chip.tsx
src/utils/hooks/useDebounce/index.ts
src/utils/hooks/useDebounce/useDebounce.ts

This PR uses the `Chip`'s label as the HTML `title` attribute and enforces a maximum width of 186px on all `Chip`s

MOS-1126 Chip tooltip

---

src/forms/FormFieldMapCoordinates/FormFieldMapCoordinates.tsx
src/forms/FormFieldMapCoordinates/MapCoordinates.stories.tsx

This PR addresses some small zoom issues and adds a knob to the `FormFieldMapCoordinates` story to aid in testing

MOS-1041 coords qa feedback

---

src/components/Form/Form.stories.mdx

This PR updates documentation to reflect recent changes to the `UploadData` interface

MOS-1177 Updates UploadData documentation

---

src/components/Form/Form.tsx

Reverts simpleviewinc/sv-mosaic#519

Revert "MOS-1104 Prevent unnecessary Form remounts"

---

automation_testing/tests/Components/Chip/chip.spec.ts
automation_testing/tests/FormFields/FormFieldAdvancedSelection/FormFieldAdvancedSelectionPlayground.spec.ts
src/components/Chip/Chip.stories.tsx
src/components/Chip/Chip.styled.ts
src/components/Chip/Chip.tsx

This PR uses the `Chip`'s label as the HTML `title` attribute and enforces a maximum width of 186px on all `Chip`s

MOS-1126 Chip tooltip (reinstated)

---

src/components/Field/FormFieldAdvancedSelection/AdvancedSelectionDrawer.tsx
src/components/Field/FormFieldDate/DateField/DateField.styled.tsx
src/components/Field/fieldUtils.ts

This PR addresses the feedback that was raised when doing QA for MOS-1175

MOS-1175 QA Fixes

---

.circleci/config.yml
Dockerfile
automation_testing/docker-compose.yml
scripts/run

MOS-1199 Upgrades to node 18

---

tsconfig.json

Ensures TS module resolution paths are transformed at build time

MOS-1197 Ensures TS paths are transformed

---

src/components/Form/formActions.ts
src/components/Form/validators.ts

Introduces min/max date validator and automatically registers it for date fields that have `inputSettings.minDate` or `inputSettings.maxDate` defined.

MOS-1178 Introduce min and max date validators

---

src/components/Button/Button.tsx
src/components/Button/ButtonTypes.tsx
src/components/Field/FormFieldAddress/Address.test.tsx
src/components/Field/FormFieldAddress/AddressDrawer/AddressDrawer.tsx
src/components/Field/FormFieldAddress/FormFieldAddress.tsx
src/components/Field/FormFieldAdvancedSelection/FormFieldAdvancedSelection.tsx
src/components/Field/FormFieldMapCoordinates/FormFieldMapCoordinates.tsx
src/components/Field/FormFieldText/FormFieldText.stories.tsx
src/components/Form/Col/fieldConfigMap.ts
src/components/Form/formActions.ts
src/components/Form/stories/DrawerForm.stories.tsx
src/components/Form/stories/FormWithLayout.stories.tsx
src/components/Form/stories/Validators.stories.tsx

- Ensures correct default validation strategy based on field type

MOS-1131 Form rehaul

---

automation_testing/tests/Components/Button/buttonPlayground.spec.ts
src/components/Button/Button.stories.tsx
src/components/Button/Button.styled.ts
src/components/Button/Button.tsx
src/theme/theme.ts

- Modifies the `Button` story to allow the toggling of a light/dark background
- Update the colours used for the white coloured button
- Have `popoverEvent` only effect popovers and not menu items or menu content

MOS-1201 QA feedback

---

src/components/Field/Field.tsx
src/components/Field/InstructionText.styled.ts
src/components/Field/InstructionText.tsx
src/components/Field/Label.tsx

Fix instructional text responsiveness to ensure that either the tooltip or adjacent instruction box is displayed at all times

MOS-1203 Fix instruction tooltip responsiveness

---

src/components/DataViewPrimaryFilter/DataViewPrimaryFilter.tsx

Updates the `DataView` active filters' button colour, since the black contained button combination has been corrected to have a black background instead of gray

MOS-1216 Update button colour

---

src/components/Field/Field.styled.ts
src/components/Field/Field.tsx
src/components/Field/FormFieldMatrix/FormFieldMatrix.styled.tsx

Ensures that field containers grow to the available space if the given field's width is `full`

MOS-1219 Matrix field width

---

src/components/Field/FormFieldMatrix/FormFieldMatrix.styled.tsx
src/components/Form/stories/FormWithLayout.stories.tsx

Removes the horizontal margin that the dataview table has when it fall inside a matrix field context

MOS-1220 Matrix field DataView margin

---

src/components/Content/Content.stories.tsx

Updates the content story to prevent the "More/Less Details" button from appearing when it doesn't need to

(Content) Updates story

---

src/components/Form/stories/FormWithLayout.stories.tsx

Updates the `FormWithLayout` story to assist with QA for MOS-1232

MOS-1232 Updates story for QA

---

automation_testing/pages/Components/Form/FormWithLayoutPage.ts
automation_testing/tests/Components/form/FormWithLayout.spec.ts

Updates tests to reflect changes in toggled sections

MOS-1232 Updates tests

---

src/components/Form/formActions.ts

Ensures values for disabled fields are not submitted by running any existing disabled toggle mechanic

MOS-1231 Disabled toggle rework

---

automation_testing/tests/Components/Content/Content.spec.ts
src/components/Content/Content.stories.tsx
src/components/Content/Content.styled.ts
src/components/Content/Content.tsx
src/components/Content/ContentRow.tsx
src/components/Content/ContentTypes.ts
src/transforms/column_transforms.tsx

Replaces `Content` row flex with grid and adds a gap between items

MOS-1240 Content padding

---

src/components/Form/Form.stories.mdx

Updates documentation to include full minimum/maximum date input setting explanation

MOS-1243 Date field documentation

---

src/components/Field/FormFieldAddress/FormFieldAddress.tsx

Fixes single address type criteria, properly allowing specific types to override a defined per type limit.

MOS-1235 Address rework issues

---

src/components/Field/FormFieldAddress/AddressDrawer/AddressDrawer.tsx
src/components/Field/FormFieldAddress/FormFieldAddress.tsx

Ensures the address' geographical state is correctly cleared out when the country value is changed.

MOS-1208 Address refactor rework

---

src/components/Field/FormFieldDate/DateField/FormFieldDate.tsx
src/components/Field/FormFieldTime/TimeField/FormFieldTime.tsx
src/components/Field/FormFieldTime/TimeField/TimeField.test.tsx

Ensures the disabled property is obeyed for both time and date fields. Adds tests for the time field.

MOS-1239 Time field rework

---

src/components/Form/stories/Playground.stories.tsx

Removes a redundant addres field from the form playground story.

MOS-1262 Remove redundant address field from playground

---

src/components/Field/FormFieldTime/TimeField/FormFieldTime.tsx
src/components/Field/FormFieldTime/TimeField/TimeField.test.tsx
src/components/Form/Form.stories.mdx

- Ensure time is not considered valid if the user has emptied the input field
- Fixes an issue regarding order of documentation

MOS-1264 Invalid time bug

---

src/components/MenuBase/MenuBase.styled.tsx
src/components/MenuBase/MenuBase.tsx

Employs more specific selector for menu paper styles to avoid applying them to the associated backdrop

MOS-1223 Bad menu styling

---

src/components/Field/fieldUtils.ts

Updates default size for text and dropdown fields from small to medium.

MOS-1267 Default field sizes

---

package.json
src/components/SideNav/SideNav.stories.mdx
src/components/SideNav/SideNav.stories.tsx
src/components/SideNav/SideNav.tsx
src/components/SideNav/SideNavTypes.ts
src/index.ts
src/utils/hooks/useToggle/useToggle.stories.mdx
src/utils/index.ts
src/utils/toggle/useToggle.ts

Employs the toggle mechanic to allow for dynamically showing or hiding `SideNav` items.

MOS-1258 SideNav toggle items

---

src/components/DataViewPrimaryFilter/DataViewPrimaryFilter.tsx

Adds title attribute to filter value to maintain cross-browser consistency when there is text overflow causing an ellipsis.

MOS-1224 Date filter value title tooltip

---

src/components/Form/Form.stories.mdx

Updates upload field documentation to include instruction for new `inputSettings`.

MOS-1275 Updates upload field documentation

---

src/components/SummaryPageTopComponent/SummaryPageTopComponent.test.tsx
src/components/SummaryPageTopComponent/SummaryPageTopComponent.tsx

Removes the arbitrary maximum action and description item checks, allowing the consumer to provide as many of these items as is necessary.

MOS-1276 Summary item limits

---

src/components/Button/Button.styled.ts

Fixes the button content box model to match the same as the neighbouring input.

MOS-1180 Address input style button sizes

---

src/components/Field/FormFieldAddress/AddressDrawer/AddressDrawer.tsx
src/components/Form/useForm/initial.ts
src/components/Form/useForm/reducers.ts
src/components/Form/useForm/useForm.ts

Addresses issues introduced in the form refactor including:
- Providing the Address field's drawer form method to the autocomplete field to support validation
- Correct instantiation of the initial form state and stable data to prevent leaks between form controllers

MOS-1255 Form rework

---

src/components/Form/Form.styled.ts
src/components/Form/Form.tsx

Remove the overlay element that is rendered when the form is disabled.

MOS-1150 Rework form disabled

---

src/components/DataViewFilterText/DataViewFilterText.styled.ts

Fixes `DataView` filter operator dropdown to calculate width based on horizontal padding.

MOS-1300 Fix DataView filter operator dropdown

---

src/components/LeftNav/LeftNav.stories.tsx
src/components/LeftNav/LeftNavMobile.tsx
src/components/LeftNav/NavWrapper.tsx

Eliminates the dual state that is present in `LeftNav` by not storing items provided to `LeftNavProps` in local state.

MOS-1297 Eliminate LeftNav dual state

---

.storybook/env-banner/env-banner.css
.storybook/env-banner/environments.js
.storybook/env-banner/escapeRegExp.js
.storybook/env-banner/index.js
.storybook/env-banner/init.js
.storybook/manager.js

Renders a banner above the Storybook interface with a background colour and text to indicate the environment that it is currently being viewed on (local grey, develop purple, qa red, staging orange or master green). It also prints the Mosaic package version in the same banner.

MOS-1149 Storybook UI banner

---

automation_testing/tests/Components/form/FormWithLayout.spec.ts
src/components/Form/stories/FormWithLayout.stories.tsx

Rewrites the entire "Form With Layout" story configuration to make it all round more coherent and better reflect what a real world form would look like.

MOS-1250 Form with layout improvements

---

src/components/Form/stories/FormWithLayout.stories.tsx

Updates story to use phone fields

MOS-1250 Rework

---

src/components/Button/Button.styled.ts
src/components/Button/Button.tsx
src/components/Button/ButtonTypes.tsx
src/components/DataView/DataView.stories.tsx
src/components/DataView/DataView.tsx
src/components/DataView/DataViewTypes.ts

Ensures that primary `DataView` actions are horizontally aligned by preserving space for those that are hidden as a result of their `show` property. As a by-product, adds support for the `invisible` property to the `Button` component which still renders the button, but hides and disables it.

MOS-1289 DataView primary action align

---

src/components/FieldWrapper/FieldWrapper.tsx
src/components/Form/validators.ts
src/utils/dom/getHtmlText.ts
src/utils/string/getTextLength.ts
src/utils/string/index.ts

Fixes bug that caused Chrome not to correctly count editor blocks. Adds support for multi code point characters.

MOS-1339 Rework

---

src/components/DataView/DataView.stories.tsx
src/index.ts

No longer exports transforms from the root entry file

MOS-1349 No longer exports transforms from the root entry file
