src/Forms/Form/Form.stories.mdx
Fixed next issues in the Form documentation
- Take validators and types to the end of documentation.
- Remove “Props (Input settings)” subsection and replace as bullet point under description subsection.
- Rename “Default settings” to data
=> MOS-618: Fix input settings from documentation

.gitignore, src/forms/FormFieldImageUpload/FormFieldImageUpload.stories.tsx, src/forms/FormFieldImageUpload/FormFieldImageUpload.test.tsx, src/forms/FormFieldImageUpload/FormFieldImageUpload.tsx
- The buttons of "View" and "Set Focus" are not going to be rendered if the `handleSetFocus` handler function is not passed through props
- The respective unit tests for this case
- Coverage directory added to `.gitignore`
=> MOS-648: Render "Set Focus" button only when the respective handler is passed

src/forms/Form/Form.tsx, src/forms/TopComponent/TopComponent.test.tsx, src/forms/TopComponent/TopComponent.tsx
- Adjustment to the TopComponent that will only render the Cancel button if its respective function is passed
- Unit tests for that case
The Save button will always be rendered since the `submit` function is defined inside the Form component. In any case, the condition was set to only show the button if the function is passed, this is in case you want to use the TopComponent independently, if that scenario it's not possible, we should remove that condition.
=> MOS 637: Render "Cancel" button conditionally

src/forms/Form/Form.stories.tsx, src/forms/FormFieldDropdownSingleSelection/FormFieldDropdownSingleSelection.styled.tsx, src/forms/FormFieldDropdownSingleSelection/FormFieldDropdownSingleSelection.tsx, src/forms/FormFieldDropdownSingleSelection/FormFieldDropdownSingleSelectionTypes.tsx
- Solves Autocomplete MUI warning of
- 
- Open any component that uses the FormFieldDropdownSingleSelection, inspect the browser console and no warning should appear.
=> MOS-645: Solves Autocomplete MUI warning

src/components/Drawer.jsx, src/forms/Form/Form.styled.ts, src/forms/TopComponent/Views/DesktopView.tsx, src/forms/TopComponent/Views/MobileView.tsx, src/forms/TopComponent/Views/ResponsiveView.tsx, src/theme/theme.ts
- The additional actions displayed on the Saved Views drawer are now shown. The problem was the `z-index` of the Drawer, the actions were being displayed correctly but behind the drawer
=> MOS-652: Fix additional actions in the Saved Views drawer

src/components/DataView/example/MultiSelectHelper.ts
- MultiSelect getSelected should not be called unless array.length > 1
=> MOS-147: MultiSelect getSelected array.length > 1

src/components/Button/Button.styled.ts, src/components/DataViewPrimaryFilter.jsx, src/components/internal/DataViewColumnControl.jsx
- Small buttons are exactly 30px height
- The right icons of the filters are 16px size
- Aditional filters have text-transform: Capitalize and non bold
- Columns button is an icon button and size small. Also has  a tooltip with text “Update columns and their order.”
=> MOS-658-Fixed button styles

dev/publish, package.json, types-only/.npmrc, types-only/package.json
- Updates on main package.json to create and copy types to types-only folder.
- Updates on types-only package.json to publish directly to npm (previously was github packages).
- Uncommented publish script for types-only.
=> MOS-619 Updated scripts to publish types-only to npm

src/components/DataView/DataViewDisplayGrid.jsx
-  Fixed up row Data View action buttons when they are as grid
=> Mos 684:  Record actions not working as expected on DataView's grid

src/components/FilterSingleSelect/FilterSingleSelect.stories.tsx, src/components/FilterSingleSelect/FilterSingleSelect.tsx, src/components/FilterSingleSelect/FilterSingleSelectTypes.ts
- Changed required prop to send inside to args prop on FilterSingleSelect component
=> MOS-679: Allow filter single select to require a value

src/components/DataView/DataViewTypes.ts, src/components/DataView/tests/bulkActionsUtils.test.ts, src/components/DataView/utils/bulkActionsUtils.ts
- Actions show attribute accepts and processes an array.
- Adds the type to the show actions attribute of: `(DataViewActionShow | boolean)[]`
- Unit tests to the filterAction helper function
=> MOS-683: Actions need to accept an array

src/components/Button/Button.stories.mdx, src/components/Drawers/Drawers.stories.mdx, src/components/LeftNav/LeftNav.stories.mdx, src/forms/Form/Form.stories.mdx, src/forms/FormFieldAddress/Address.stories.mdx, src/forms/FormFieldAdvancedSelection/AdvancedSelection.stories.mdx, src/forms/FormFieldCheckbox/FormFieldCheckbox.stories.mdx, src/forms/FormFieldColorPicker/ColorPicker.stories.mdx, src/forms/FormFieldDropdownSingleSelection/FormFieldDropdownSingleSelection.stories.mdx, src/forms/FormFieldImageUpload/FormFieldImageUpload.stories.mdx, src/forms/FormFieldImageVideoLinkDocumentBrowsing/ImageVideoLinkDocumentBrowsing.stories.mdx, src/forms/FormFieldMapCoordinates/MapCoordinates.stories.mdx, src/forms/FormFieldPhoneSelectionDropdown/FormFieldPhoneSelectionDropdown.stories.mdx, src/forms/FormFieldRadio/FormFieldRadio.stories.mdx, src/forms/FormFieldTable/Table.stories.mdx, src/forms/FormFieldText/FormFieldText.stories.mdx, src/forms/FormFieldTextArea/FormFieldTextArea.stories.mdx, src/forms/FormFieldToggleSwitch/FormFieldToggleSwitch.stories.mdx
- Fix docs in export for Forms
- Fix broken links the points to the component's props at the `.mdx` files
=> MOS-690: Fix export of Forms in docs and broken links to components props

src/forms/FormFieldImageUpload/ImageUploadCanvas/ImageUploadCanvas.tsx, src/forms/MenuFormFieldCard/MenuFormFieldCard.tsx, src/forms/MenuFormFieldCard/MenuFormFieldCardTypes.ts
- Deleted "getContentAnchorEl" prop from MenuFormFieldCard.tsx that was causing an issue when running unit tests (this prop doesn't even exist anymore on newest mui version).
- Updated return statement of useEffect in ImageUploadCanvas causing issues when running unit tests related to an unmounted ref.
=> Fixed unit test for MenuFormFieldCard

src/components/Button/Button.styled.ts, src/components/internal/DataViewViewControls.jsx
- Limited the dropdown’s text of the Dataview title to 300px and 2 lines max, whatever exceeds must show “…”
- Added p tag to button label
=> Mos 61 limit dropdown text

src/components/internal/DataViewFilterMultiselectDropdownContent.jsx
- Fix: Load more button for categories disappears when clicking clear
=> MOS-69: Load more button for categories disappears when clicking clear

src/forms/Form/Col.tsx, src/forms/Form/Form.stories.tsx, src/forms/Form/Form.tsx, src/forms/Form/FormLayout.tsx, src/forms/Form/FormTypes.tsx, src/forms/Form/Row.tsx, src/forms/Form/Section.tsx, src/forms/FormNav/FormNav.styled.tsx, src/forms/FormNav/FormNav.test.tsx, src/forms/FormNav/FormNav.tsx, src/forms/FormNav/FormNavTypes.tsx, src/forms/TopComponent/TopComponent.tsx, src/forms/TopComponent/Views/DesktopView.tsx, src/forms/TopComponent/Views/ResponsiveView.tsx
- Replace the use of classes to select a section with refs
- Display the right scroll button conditionally
- Use the section index instead of the title to get its id
- Replace `window.replace` with `scrollIntoView` using a ref
- CSS logic refactored
- Rename **fieldsLayoutPos** to **rows**
- Update the typeDef for the “fields” from  (string | FieldDef)[ ][ ][ ] to string[ ][ ][ ].
- Debouncing scroll listener function
- Throwing an error message to indicate that an undefined field was declared. “No field declared for field name 'X' at row 1, column 10 in section 0.”
=> MOS-701: Sections refactor

src/components/internal/DataViewViewControls.jsx
- Fixed extra magin issue with long words
=> MOS-742: DataView view title should only be one line

src/forms/FormFieldAddress/AddressDrawer/AddressDrawer.tsx
- Updated postal code with trim function to prevent users from writing empty spaces before and after it.
=> Added trim to postalCode to prevent empty spaces before and after

changelog.md, src/forms/FormFieldColorPicker/ColorPicker.styled.tsx, src/forms/FormFieldColorPicker/FormFieldColorPicker.tsx
* Added mousedown event that listens when clicking outside of color picker, this allows users to scroll even with the picker open.
=> Updated scrollable logic

src/components/DataView/DataView.test.tsx, src/components/DataView/DataViewFilters.tsx, src/components/DataView/DataViewTypes.ts, src/components/DataView/example/DataViewKitchenSink.tsx, src/components/DataViewFilterText/DataViewFilterText.tsx
- Refactor to send comparisonDefault prop to DataViewFilterText component
- Unit test case to check it throw an error when developer send an invalid comparison
=> Mos-761: Text default comparison not functional

automation_testing/pages/BasePage.ts, automation_testing/pages/Components/Checkbox/CheckboxPage.ts, automation_testing/pages/Components/Chip/ChipPage.ts, automation_testing/pages/Components/RadioButton/RadioButtonPage.ts, automation_testing/pages/Components/SummaryPageTopComponent/SummaryPageTopComponentPage.ts, automation_testing/pages/Components/ToggleSwitch/ToggleSwitchPage.ts, automation_testing/tests/Components/Button/button.spec.ts, automation_testing/tests/Components/Checkbox/checkbox.spec.ts, automation_testing/tests/Components/Chip/chip.spec.ts, automation_testing/tests/Components/RadioButton/radioButton.spec.ts, automation_testing/tests/Components/SummaryPageTopComponent/summaryPageTopComponent.spec.ts, automation_testing/tests/Components/ToggleSwitch/toggleSwitch.spec.ts, src/components/Button/Button.styled.ts, src/components/Checkbox/Checkbox.styled.ts, src/components/Chip/Chip.styled.ts, src/components/RadioButton/RadioButton.styled.tsx, src/components/SideNav/SideNav.styled.tsx, src/components/SummaryPageTopComponent/SummaryPageTopComponent.styled.tsx, src/components/ToggleSwitch/ToggleSwitch.styled.tsx, src/forms/FormFieldChipSingleSelect/FormFieldChipSingleSelect.test.tsx
Update references to the simplyGold color
Components that were updated
- Checkbox
- Button
- Chip
- RadioButton
- SideNav
- SummaryPageTopComponent
- ToggleSwitch - This won't have opacity
Since the new colors are plain RGB values and not RGBA the background when hovering over the switch thumb will not have opacity. I tried to add the opacity by doing something like the following but the tumb was also affected by the opacity of the background color
```
.MuiSwitch-colorPrimary {
&.Mui-checked {
&:hover {
background-color: ${theme.newColors.simplyGold["100"]};
opacity: 30%
}
}
}
```
=> MOS-838: Update references to simply gold

src/components/Chip/Chip.styled.ts, src/components/Form/Form.stories.mdx, src/components/Form/Form.stories.tsx, src/forms/FormFieldAddress/Address.stories.tsx, src/forms/FormFieldAddress/Address.test.tsx, src/forms/FormFieldAddress/AddressDrawer/AddressDrawer.tsx, src/forms/FormFieldAddress/AddressTypes.tsx, src/forms/FormFieldAddress/FormFieldAddress.tsx, src/forms/FormFieldAddress/utils/optionGetters.ts
- Updated FormFieldAddress types to now require getOptionsCountries and getOptionsStates callbacks.
- Updated AdressDrawer to get the corresponding country and state options from these callbacks rather than the countries JSON file.
- Updated Form and Address stories and unit tests to include the new props.
- Created a utils file that exports those 2 helper functions to be reused both in stories and unit tests.
=> Mos 856 Address field country/state updates

src/components/DataView/DataViewTBody.tsx, src/components/DataView/DataViewTHead.tsx, src/components/DataView/DataViewTd.tsx, src/components/DataView/DataViewTr/DataViewTr.tsx, src/components/DataView/example/DataViewKitchenSink.tsx
- The right padding of the table header should be 8px.
- Font-color for table header should be #1A1A1A and the font-weight should be 510.
- Font-color for each row should be #1A1A1A and the font-weight should be 400.
- The drag and drop icon color should be #1A1A1A in the table, fin the columns settings it is correct.
- Title column should not have the black line below and the name of the column should not go in bold either.
- Change download icon
- Bottom border color of each row should be solid rgba(240, 242, 245, 1).
=> MOS-870: Fix styles found during QA process

src/components/DataViewFilterDropdown/DataViewFilterDropdown.styled.ts, src/components/DataViewFilterDropdown/DataViewFilterDropdown.tsx, src/components/DataViewFilterText/DataViewFilterText.styled.ts, src/forms/FormFieldText/FormFieldText.styled.tsx
Fixes the following points found by QA
- Verify input-placeholder style(font-family, font-color, font-size,font-weight).
Font family and font size were correct
-  Filter unfolded- Search style should be:
Border: 1px solid rgba(240, 242, 245, 1).
Box-shadow: 0px 2px 6px 0px rgba(26, 26, 26, 0.25). This color is our almostBlack, but we have not defined a variant opacity of 25%, so the value chosen was with 20% opacity since is the closest one.
Border-radius 5px.
=> MOS-884: Apply styles to Filter Text

src/components/DataView/DataView.tsx, src/components/DataView/DataViewFilters.tsx, src/components/DataView/example/DataViewKitchenSink.tsx
Throws a descriptive error when an invalid column or active filter is passed to the DataView, indicating which column or filter is not valid.
In DataViewKitchenSink.tsx add a random value to activeFilters or activeColumns and the custom error should be displayed.
```
const rootDefaultView: DataViewProps["savedView"] = {
id: "default",
label: "All",
type: "default",
state: {
limit: 25,
skip: 0,
filter: {},
sort: {
name: "title",
dir: "asc"
},
display: "list",
activeFilters: ["foo"], <---
activeColumns: ["image", "title", "categories", "created", "bar"] <---
}
};
```
=> MOS-886: Show descriptive error for invalid column or active filter

src/components/DataView/DataView.test.tsx, src/components/Form/Form.stories.tsx, src/components/Form/Form.tsx, src/components/Form/Section.tsx, src/forms/FormNav/FormNav.test.tsx, src/forms/FormNav/FormNav.tsx, src/forms/FormNav/FormNavTypes.tsx, src/forms/TopComponent/TopComponent.test.tsx, src/forms/TopComponent/TopComponent.tsx, src/forms/TopComponent/Views/DesktopView.tsx, src/forms/TopComponent/Views/ResponsiveView.tsx
Changes scroll behavior for the Form sections.
I've defined sections of different sizes and tested the section highlight when clicking or scrolling. Example of mock sections
```
const sections = useMemo(() => [
{
title: "Section 1",
description: "Description for section 1",
fields: [
// row 1
[["text1"], ["text2"], ["text3"]],
// row 2
[["check"], ["text4"], ["color"]],
[[]],
// row 3
[["toggleSwitch"], ["imageUpload"]]
]
},
{
title: "Section 4",
description: "Description for section 3",
fields: [
// row 1
[[], [], []],
// row 2
[[], [], []],
[[]],
// row 3
[[], []]
]
},
{
title: "Section 2",
description: "Description for section 2",
fields: [
// row 1
[["check"], ["toggleSwitch"], ["color"]],
// row 2
[[], [], []],
// row 3
[[]],
// row 4
[[], ["textEditor"]]
]
},
{
title: "Section 3", …
```
=> MOS-876: Form sections pickers scroll behaviour fixed

src/components/Form/Form.tsx
Disables form inputs autocomplete
- Tested on Chrome and Firefox
- When testing on Chrome make sure you have the autocomplete enabled to avoid a positive false result
=> MOS-895: Disables form autocomplete

src/components/Form/Form.stories.tsx, src/components/Form/Form.test.tsx, src/components/Form/Form.tsx, src/components/Form/formActions.ts, src/components/Form/formUtils.ts
Disabling form logic changed when it is prepopulated.
Go to the Form playground story and prepopulate it. You should see the screen block for a second and then all the fields filled.
=> MOS-900: Form disable logic on load not disabling correctly

src/components/Button/Button.styled.ts, src/components/Chip/Chip.styled.ts, src/components/Field/InstructionText.styled.ts, src/components/InstructionText/InstructionText.styled.ts, src/components/Popover/Popover.stories.tsx, src/components/Snackbar/Snackbar.styled.tsx, src/components/ToggleSwitch/ToggleSwitch.styled.tsx, src/forms/FormFieldAddress/AddressCard/AddressCard.styled.tsx, src/forms/FormFieldAdvancedSelection/AdvancedSelection.styled.tsx, src/forms/FormFieldColorPicker/ColorPicker.styled.tsx, src/forms/FormFieldDate/DatePicker/DatePicker.styled.tsx, src/forms/FormFieldPhoneSelectionDropdown/FormFieldPhoneSelectionDropdown.styled.tsx, src/forms/FormFieldText/FormFieldText.styled.tsx, src/forms/FormFieldTextArea/FormFieldTextArea.styled.tsx, src/forms/FormFieldTextEditor/FormFieldTextEditor.styled.ts, src/theme/theme.ts
Replaces simplyGray references with the new color syntax.
simplyGrayOpacity (190, 190, 190, 0.3) was replaced with the variant using 0.2 opacity since we do not have a 0.3 variant.
=> MOS-848: Update all references to simply gray

src/components/DataViewFilterDate/DataViewFilterDate.stories.tsx, src/components/DataViewFilterDate/DataViewFilterDate.test.tsx, src/components/DataViewFilterDate/DataViewFilterDate.tsx, src/components/DataViewFilterDate/DataViewFilterDateDropdownContent.tsx, src/components/DataViewFilterDate/DataViewFilterDateTypes.ts, src/components/DataViewFilterMultiselect/DataViewFilterMultiselect.styled.tsx
- Added "magic values" functionality to DataViewFilterDate. This works by passing an options array (of MosaicLabelValues) to the arguments of the filter.
- Filter will now return { option: string } when one of the magic values get selected or { rangeStart: date, rangeEnd: date } when manually adding the dates.
- Clicking on one of the magic values will automatically select the option. Users don't have to click on "Apply"
- Updated types and interfaces to better match what's required.
=> Mos 902 Add pre-filled magic values to the date filter

automation_testing/tests/Components/dataview/data_view.spec.ts
https://simpleviewtools.atlassian.net/browse/MOS-452
Added scenario validating the issue found.
=> TAE -MOS-452 - Clicking User Options and then clicking out does not collapse the tool tip

src/components/DataViewFilterDate/DataViewFilterDate.tsx, src/components/DataViewFilterDate/DataViewFilterDateDropdownContent.tsx
- Added extra condition to verify if data is being propped to the filter.
- Fixed condition that was sending back "undefined" when clicking "onApply".
- Filter now unselecting any magic value when changing the custom values.
- Filter now throwing error when manually typing an invalid date.
=> MOS-902 Fixed issue with type guard in FilterDate

src/components/Form/Form.stories.mdx, src/forms/FormFieldAddress/Address.stories.mdx, src/forms/FormFieldAdvancedSelection/AdvancedSelection.stories.mdx, src/forms/FormFieldCheckbox/FormFieldCheckbox.stories.mdx, src/forms/FormFieldChipSingleSelect/FormFieldChipSingleSelect.stories.mdx, src/forms/FormFieldColorPicker/ColorPicker.stories.mdx, src/forms/FormFieldDate/DateField/DateField.stories.mdx, src/forms/FormFieldDropdownSingleSelection/FormFieldDropdownSingleSelection.stories.mdx, src/forms/FormFieldImageUpload/FormFieldImageUpload.stories.mdx, src/forms/FormFieldImageVideoLinkDocumentBrowsing/ImageVideoLinkDocumentBrowsing.stories.mdx, src/forms/FormFieldMapCoordinates/MapCoordinates.stories.mdx, src/forms/FormFieldPhoneSelectionDropdown/FormFieldPhoneSelectionDropdown.stories.mdx, src/forms/FormFieldRadio/FormFieldRadio.stories.mdx, src/forms/FormFieldTable/Table.stories.mdx, src/forms/FormFieldText/FormFieldText.stories.mdx, src/forms/FormFieldTextArea/FormFieldTextArea.stories.mdx, src/forms/FormFieldTextEditor/FormFieldTextEditor.stories.mdx, src/forms/FormFieldToggleSwitch/FormFieldToggleSwitch.stories.mdx
- Fields props docs are now documented with tables
- Adds reference to each field that implements the FieldDef interface
- Adds a link to each field readme story that redirects to its example on the Form docs
=> Mos 910 improve documentation of form fields

src/components/DataView/DataViewTr/DataViewTr.tsx, src/forms/FormFieldPhoneSelectionDropdown/FormFieldPhoneSelectionDropdown.test.tsx
Uses the original data id and it's converted to a string to avoid this warning even when a number is used as an id.
Look for the Accessibility record raw data within the ´rawData.json´ file and modify its id to a number
Inspect the console and the warning should not appear.
=> MOS-942: Invariant failed draggable requires a draggable id

src/components/SummaryPageTopComponent/SummaryPageTopComponentTypes.ts
- Updated to optional the favorite prop for SummaryPageTopcomponent
=> MOS-957: Favorite shouldn't be required on SummaryPageTopComponent

automation_testing/tests/Components/dataview/data_view.spec.ts, automation_testing/utils/data/knobs.ts, src/components/DataView/DataView.tsx, src/components/DataView/DataViewTHead.tsx
- Removed validBulkActions conditions from dataView
=> MOS-947: BulkActions shouldn't be required to render checkboxes in DataView

src/components/Field/Field.test.tsx, src/components/Field/Field.tsx, src/components/Field/FieldTypes.tsx, src/components/Form/Form.stories.mdx, src/forms/FormFieldText/FormFieldText.stories.tsx
- Removed extra maxCharacters fieldDef from FormFieldText component
=> MOS-955: Remove maxCharacter prop from FieldDefBase

automation_testing/pages/BasePage.ts, automation_testing/pages/Components/Chip/ChipPage.ts, automation_testing/tests/Components/Chip/chip.spec.ts, src/components/Chip/Chip.stories.tsx, src/components/Chip/Chip.tsx
- Removed clickable and disableRipple from Chip component
- Added onClick knob to playground story 
- Added new chips examples to kitchensink
=> MOS-958: Chip should not show "click" pointer if onClick is not passed

src/components/DataView/DataView.stories.tsx, src/components/DataView/DataViewActionsRow/DataViewActionsRow.tsx, src/components/DataView/DataViewDisplayGrid/DataViewDisplayGrid.tsx, src/components/DataView/DataViewTHead.tsx
- Fixes the conditionally displayed of bulkActions on the Grid view.
- Fixes DOM warning about the `th` `colsSpan`  attribute seen as a boolean instead of a number
- Adds validation to `checked` prop that caused Grid view to break since this prop is optional.
=> MOS-947: Fix bulk actions display on grid view

automation_testing/pages/BasePage.ts, automation_testing/pages/Components/DataView/DataViewPage.ts, automation_testing/pages/Components/Form/PlaygroundPage.ts, automation_testing/pages/Components/SummaryPageTopComponent/SummaryPageTopComponentPage.ts, automation_testing/tests/Components/SummaryPageTopComponent/summaryPageTopComponent.spec.ts, automation_testing/tests/Components/dataview/data_view.spec.ts, automation_testing/tests/Components/form/playground.spec.ts, automation_testing/utils/data/knobs.ts, src/components/DataView/DataView.stories.mdx, src/components/DataView/DataView.stories.tsx, src/components/DataView/DataView.tsx, src/components/DataView/DataViewTitleBar/DataViewTitleBar.styled.ts, src/components/DataView/DataViewTitleBar/DataViewTitleBar.tsx, src/components/DataView/DataViewTitleBar/DataViewTitleBarTypes.ts, src/components/DataView/DataViewTypes.ts, src/components/Form/Form.stories.mdx, src/components/Form/Form.stories.tsx, src/components/Form/Form.tsx, src/components/Form/FormTypes.tsx, src/components/SummaryPageTopComponent/SummaryPageTopComponent.stories.tsx, src/components/SummaryPageTopComponent/SummaryPageTopComponent.styled.tsx, src/components/SummaryPageTopComponent/SummaryPageTopComponent.tsx, src/components/SummaryPageTopComponent/SummaryPageTopComponentTypes.ts, src/forms/TopComponent/TopComponent.tsx, src/forms/TopComponent/TopComponentTypes.tsx, src/forms/TopComponent/Utils/TitleWrapper.tsx, src/forms/TopComponent/Views/DesktopView.tsx, src/forms/TopComponent/Views/MobileView.tsx, src/forms/TopComponent/Views/ResponsiveView.tsx
- Updated TittleWrapper component so it receives "onBack" prop
- Added onBack knobs to DataView, Form, and SummaryPageTopComponent
=> Mos 967:  Add back capability to Form, DataView and Summary Top

automation_testing/pages/Components/SideNav/SideNavPage.ts, automation_testing/tests/Components/SideNav/sideNav.spec.ts, automation_testing/utils/data/knobs.ts, src/components/Form/Form.tsx, src/components/SideNav/SideNav.stories.mdx, src/components/SideNav/SideNav.stories.tsx, src/components/SideNav/SideNav.styled.tsx, src/components/SideNav/SideNav.tsx, src/components/SideNav/SideNavTypes.ts, src/forms/FormFieldPhoneSelectionDropdown/FormFieldPhoneSelectionDropdown.tsx
- Replaces FormNav with SideNav in the Form on a big desktop view.
- Adds attrs prop to the SideNav to be able to configure the anchor element.
- Adds table of SideNav props as documentation.
- Updates SideNav's styles.
=> MOS-977: Use SideNav in the Form on a big desktop view

automation_testing/tests/FormFields/formFieldNumberTable.spec.ts, automation_testing/utils/data/knobs.ts, src/components/Form/Form.stories.mdx, src/forms/FormFieldNumberTable/FormFieldNumberTable.stories.tsx, src/forms/FormFieldNumberTable/FormFieldNumberTable.styled.tsx, src/forms/FormFieldNumberTable/FormFieldNumberTable.test.tsx, src/forms/FormFieldNumberTable/FormFieldNumberTable.tsx, src/forms/FormFieldNumberTable/FormFieldNumberTableTypes.ts
- Adds displaySumColumn and displaySumRow optional props to know whether to render the totals or not
- Adds unit tests for this matter
- Updates related docs
=> MOS-1015: Make the number table summing row and column optional

automation_testing/tests/Components/form/playground.spec.ts, src/components/Checkbox/Checkbox.styled.ts, src/components/Field/Field.tsx, src/components/Field/Label.tsx, src/components/Form/Col.tsx, src/components/Form/formActions.ts, src/forms/FormFieldCheckbox/FormFieldCheckbox.styled.ts, src/theme/theme.ts
- Removed "disabled" from Label component so it always renders almostBlack
- Updated "validateField" action to return if the field is disabled
- Updated error in Col.tsx to not get passed to Fields when disabled
- Removed "labelDisabled" color from theme file
=> Mos 1009 Overall disabled mechanic changes

automation_testing/tests/FormFields/formFieldDropdownSingleSelection.spec.ts, src/forms/FormFieldDropdownSingleSelection/FormFieldDropdownSingleSelection.styled.tsx
Moves misplaced padding to fix the dropdown's click target to be the input element.
=> MOS-1020: Click targeting of dropdown input is off

src/components/Field/Field.styled.ts, src/components/Form/Form.stories.tsx, src/components/Form/Form.tsx, src/components/Form/Section.tsx, src/components/SideNav/SideNav.tsx, src/forms/FormFieldPhoneSelectionDropdown/FormFieldPhoneSelectionDropdown.test.tsx
- Fixes Field wrapper to take the 100% width to not overlap fields located in the adjacent column
- Fixes PhoneDropdownSelection unit tests
- Go to the Form Playground story and set at least 1 section using the respective knob
- A long string is being used on a chip to show that the Filed width is being respected
=> MOS-1001: Form columns not constraining correctly

automation_testing/tests/Components/SummaryPageTopComponent/summaryPageTopComponent.spec.ts, src/forms/TopComponent/Utils/TitleWrapper.tsx
- Adds the title HTML property to the TitleWrapper that is used as page, DV and Form header/title
=> MOS-1039: Title in PageHeader should have tooltip

src/components/Form/formUtils.ts, src/forms/FormFieldMapCoordinates/MapCoordinatesDrawer/MapCoordinatesDrawer.tsx, src/forms/FormFieldTable/TableTypes.ts, src/forms/FormFieldTable/tableUtils.ts, src/types/index.ts
Updates types of the `useForm` hook
When trying to define `MosaicObject` as a type for `state.data` the following typescript errors happened, among many others.
With a union type of `string | Element`
With an array
And this is because the `MosaicObject` type definition is `{ [key: string]: unknown }`. The thing is that when using `unknown `, we must perform additional type checks or assertions to ensure that the value has the expected type before using it. That's why the type of `data` remained as `any`.
=> MOS-1019: Updates types of the useForm hook

src/components/DataViewFilterMultiselect/DataViewFilterMultiselectTypes.ts, src/components/Form/Form.stories.tsx, src/forms/FormFieldAdvancedSelection/AdvancedSelection.stories.tsx, src/forms/FormFieldAdvancedSelection/AdvancedSelectionDrawer.tsx, src/forms/FormFieldAdvancedSelection/AdvancedSelectionTypes.tsx
- Exports GetOptions type that is used by the AdvancedSelection and the DataViewFilterMultiSelect
- Adds type guards to AdvancedSelection to differentiate between local and external options.
=> MOS-1021: AdvancedSelection getOptions is not properly typed

automation_testing/pages/Components/DataView/DataViewPage.ts, automation_testing/tests/Components/dataview/DataView.spec.ts, automation_testing/utils/data/knobs.ts, src/components/DataView/DataView.stories.tsx, src/components/DataView/DataViewFilters/DataViewFilters.test.tsx, src/components/DataView/DataViewFilters/DataViewFilters.tsx
- Updated logic for rendering activeFilters in DataViewFilters.tsx
- Added knob for showing active filters loaded on a different order than the regular filters array.
=> MOS-1044 DataView activeFilters displaying in the wrong order

automation_testing/tests/Components/Content/Content.spec.ts, automation_testing/utils/data/knobs.ts, src/components/Content/Content.stories.tsx, src/components/Content/Content.test.tsx, src/components/Content/Content.tsx
- Updated Content's playground story to include "undefined" as a value for buttons.
- Updated unit tests to account for undefined scenario.
- Fixed conditional that throwed an error when no buttons get passed.
=> MOS-1061 MOSAIC BUG for version 22 - Undefined buttons in Content component causes TypeError

src/forms/FormFieldDate/DateField/FormFieldDate.tsx
- Updated logic in FormFieldDateField to reset time to 00:00:00 when showTime is not provided / is false. This ensures no matter what time the back end passes to the field, if it's not active we will not return it, preventing time-zone changes.
=> Mos 1051 - FormFieldDate inconsistency when value has time

src/components/DataViewFilterMultiselect/DataViewFilterMultiselectDropdownContent.tsx, src/components/Drawer/Drawer.tsx, src/forms/FormFieldAdvancedSelection/AdvancedSelectionDrawer.tsx, src/forms/FormFieldAdvancedSelection/AdvancedSelectionTypes.tsx, src/forms/FormFieldAdvancedSelection/FormFieldAdvancedSelection.tsx
This PR
- Removes the state dependency within the Advanced Selection form field component
- Removes behaviour that prompts user about unsaved changes when closing the draw
- Prevents clicks to the draw backdrop from closing the draw
=> MOS-1058 bug scrub

src/utils/hooks/useScrollSpy.ts
This PR adds the `{ passive: true }` option to the `addEventListener` that listens for wheel events.
=> MOS-975 - Adds passive: true option to addEventListener

src/utils/hooks/useScrollSpy/useScrollSpy.ts, src/utils/math/clamp.ts
This PR introduces a minimum scroll duration and fixes the scroll target offset for `useScrollSpy`
=> MOS-975 Clamp scroll duration and fix extra offset

src/forms/FormNav/FormNav.tsx
This PR prevents the default action taken when the mobile section navigation items are clicked
=> MOS-975 Fix mobile section nav default event

src/components/ButtonRow/ButtonRow.styled.tsx, src/components/DataView/DataView.stories.mdx, src/components/DataView/DataView.stories.tsx, src/components/DataView/DataView.tsx, src/components/DataView/DataViewTypes.ts, src/forms/FormFieldMatrix/FormFieldMatrix.stories.tsx, src/forms/FormFieldMatrix/FormFieldMatrix.styled.tsx, src/forms/FormFieldMatrix/FormFieldMatrix.tsx
This PR makes changes to:
- The `DataView` component, which now takes an optional `noResults` property. When there is no data to display, this component will be rendered if provided. If it is not provided, a generic string will be rendered. It also addresses a small issue where the actions row renders even though there are no children
- The `FormFieldMatrix` component, which will now display the integrated `DataView` component, even when there are no matrix items selected.
=> MOS-1073 matrix padding

src/components/DataView/DataViewFilters/DataViewFilters.tsx, src/components/Field/FieldTypes.tsx, src/components/Form/Col.tsx, src/components/Form/formUtils.ts, src/constants/formats.ts, src/constants/index.ts, src/forms/FormFieldDate/DateField/DateField.stories.tsx, src/forms/FormFieldDate/DateField/FormFieldDate.tsx, src/forms/FormFieldDate/DatePicker/DatePicker.tsx, src/forms/FormFieldDate/DatePicker/DatePickerTypes.tsx, src/forms/FormFieldDate/TimePicker/TimePicker.tsx, src/utils/date/index.ts, src/utils/date/isValidDate.ts, src/utils/date/matchTime.ts, src/utils/date/sanitizeInputDate.ts, src/utils/date/textIsValidDate.ts
This PR modifies the FormFieldDate so that it emits a date object based on the timezone of the user's browser. It also adds a layer of input validation when the user is changing the date or time fields using their keyboard. Additionally, it shows more informative hints where appropriate.
Note that:
- These hints currently show too early whilst the user is typing, instead of when the field loses focus
- The hints can be flaky due to the form system not having named errors
Both of these are part of a larger form issue, that is being addressed in a refactor for this [ticket](https://simpleviewtools.atlassian.net/browse/MOS-1131)
=> MOS-1059 Date field fixes

src/components/Form/formActions.ts, src/components/Form/formUtils.ts
This PR addresses a bug that was introduced in MOS-1059 where, in some scenarios, fields are not revalidated after user has fixed errors, preventing the form from ever being submitted.
=> Swaps out field validation actions for correct invalidate action

src/components/Form/formActions.ts
This PR adds an optional chain to the `extraArgs.fieldMap` reference to prevent throwing errors.
=> MOS-1148 Add optional chain to field map when validating

src/components/Form/Form.styled.ts, src/components/Form/Form.tsx, src/components/Form/formActions.ts, src/components/Form/formUtils.ts, src/components/Form/stories/Playground.stories.tsx, src/forms/FormFieldUpload/FormFieldUpload.tsx
This PR adds support for a form loading queue. This can be used to prevent submissions when one or more components is in a loading state. It also has the `FormFieldUpload` component utilise the new loading queue functionality to prevent users from submitting the form whilst file uploads are in progress.
=> MOS-1120 Implement a form loading queue

src/components/Form/stories/Playground.stories.tsx, src/forms/FormFieldAddress/Address.styled.tsx, src/forms/FormFieldAddress/FormFieldAddress.tsx
This PR modifies the `FormFieldAddress` field to bring the style more in line with the existing repeatable field components. It removes the large grey wasted space surrounding the "Add Address" button and displays the button below the address items. It also removes the button entirely when the address item limit has been reached.
=> MOS-1125 Improve FormFieldAddress UI/UX

src/components/DataViewFilterDate/DataViewFilterDate.stories.mdx, src/components/DataViewFilterDate/DataViewFilterDate.tsx, src/components/DataViewFilterDate/DataViewFilterDateDropdownContent.tsx, src/components/DataViewFilterDate/DataViewFilterDateTypes.ts, src/components/Form/Form.stories.mdx, src/forms/FormFieldDate/DateField/DateField.stories.tsx, src/forms/FormFieldDate/DateField/DateFieldTypes.tsx, src/forms/FormFieldDate/DateField/FormFieldDate.tsx, src/forms/FormFieldDate/DatePicker/DatePicker.tsx, src/forms/FormFieldDate/DatePicker/DatePickerTypes.tsx
This PR adds support for a custom `Datepicker` minimum date. By default, MUI sets this minimum date to 01/01/1900, but setting this prop will allow for it to be earlier or later.
=> MOS-1127 mindate support

src/components/DataView/DataViewFilters/DataViewFilters.tsx
This PR ensures the `DataView` filter order is preserved when the user is making filter modifications
=> MOS-1065 Preserve DataView filters throughout modifications

src/components/Form/Form.tsx, src/components/Form/formUtils.ts
This PR changes the form controller's initial state to make the form disabled by default. It also adds `aria-*` labels for both accessibility and ease of testing.
=> MOS 1053 Form status and aria attributes

src/components/Form/Form.stories.mdx, src/forms/FormFieldUpload/FormFieldUpload.stories.tsx, src/forms/FormFieldUpload/FormFieldUpload.tsx, src/forms/FormFieldUpload/FormFieldUploadTypes.ts
This PR adds support for throwing errors on `onFileAdd` and deprecates the `onError` callback
=> MOS 1088 Upload catch

src/components/Card/Card.stories.tsx, src/components/Content/Content.stories.mdx, src/components/Content/Content.styled.ts, src/components/Content/Content.tsx, src/components/Content/ContentField.tsx, src/components/Content/ContentRow.tsx, src/components/Content/ContentTypes.ts, src/components/DataViewFilterDate/DataViewFilterDate.tsx, src/components/Form/Form.stories.mdx, src/components/Form/FormTypes.tsx, src/components/Form/Section.tsx, src/constants/formats.ts, src/forms/FormFieldDate/DatePicker/DatePicker.tsx, src/transforms/column_transforms.tsx, src/types/index.ts
- Refactors the `Content` component, splitting nested functions into components of their own rather than redefining on each render
- Minimises reliance on hard coded date format value, opting for the `DATE_FORMAT_FULL` constant for now.
- Introduces the `MosaicGridConfig` type to replace the reuse of `string[][][]` across the board.
=> MOS-1098 Refactors the content component

src/components/Form/Form.tsx
This PR slightly restructures `<Form />`'s nested components to prevent unnecessary remounts
=> MOS-1104 Prevent unnecessary Form remounts

src/components/Content/Content.stories.tsx, src/components/Content/ContentRow.tsx
This PR ensures `Content` items with empty array values show the `<Blank />` component rather than nothing at all
=> MOS-1117 Empty content array

src/forms/FormFieldUpload/FormFieldUpload.stories.tsx, src/forms/FormFieldUpload/FormFieldUpload.tsx, src/forms/FormFieldUpload/FormFieldUploadTypes.ts, src/utils/classes/FileExtensions.ts, src/utils/classes/index.ts
This PR adds support for file extension restriction. `FormFieldUpload` fields now allow an `accept` property on their input settings. This will do the following:
- Provide the `accept` attribute to the underlying `input` element, assisting the user when selecting files to upload
- Show an error for the file card if the chosen file's format is not in the list of accepted file formats
Note: this does not check the file's mime type and relies solely on the chosen file name's extension.
=> MOS-1132 Adds file extension restriction support to FormFieldUpload

src/forms/FormFieldUpload/FormFieldUpload.tsx, src/utils/classes/FileExtensions.ts, src/utils/string/index.ts, src/utils/string/joinAnd.ts
This PR updates the message that is displayed when a user attempts to upload a file to a `FormFieldUpload` field that has an invalid extension.
=> MOS-1132 Update form file extension error message

src/components/ButtonRow/ButtonRow.tsx, src/forms/TopComponent/Views/DesktopView.tsx, src/forms/TopComponent/Views/MobileView.tsx
This PR makes changes to assist with unit and automation tests:
- Adds the `data-testid="form-header"` to the form headers container element on both desktop and mobile layouts
- Adds the `role="toolbar"`
=> MOS-1054 Form roles for testing

src/forms/FormFieldNumberTable/FormFieldNumberTable.test.tsx, src/forms/FormFieldNumberTable/FormFieldNumberTableTypes.ts
This PR updates `FormFieldNumberTable` types to support `ReactNode` labels, titles and subtitles.
=> MOS-1135 Updates number table types to support ReactNode labels

src/components/Form/Form.tsx, src/forms/TopComponent/TopComponent.styled.ts
This PR avoids draws closing unexpectedly by not rerendering `Form` every time the view system's breakpoint changes.
=> MOS-1104 Prevent unnecessary Form rerenders

src/components/Form/Col/Col.tsx, src/components/Form/formActions.ts, src/components/Form/validators.ts
This PR modifies the max character behaviour that the text field uses. Instead of limiting the amount of characters to the `maxCharacter` amount, the user can exceed the amount but the character counter will turn red and the field will have an error. The behaviour is handled by a validator, so the form cannot be submitted whilst the count is exceeded.
=> MOS-1119 Implements new value count validator

src/components/Form/formUtils.ts, src/components/Form/stories/CopyField.stories.tsx
Prevents returning a new state if the field's touched property matches the incoming boolean when setting field value.
=> MOS-1196 touched bug

src/components/Form/formActions.ts
Removed the clearing of the `touched` object when a form with valid data is submitted
=> MOS-1195 Removes touched reset on form submission

src/components/Form/formActions.ts, src/components/Form/formUtils.ts
Avoids dispatching an extraneous action to mark fields as touched, but instead provides the touched flag to the change reducer so that it can handle the touched flag with just one new state.
=> MOS-1198 Prevents extra form touch dispatch

src/components/Field/Label.tsx, src/components/Form/Form.styled.ts, src/components/Form/Form.tsx, src/components/Form/FormTypes.tsx, src/components/Form/Section/SectionStyled.tsx, src/components/Form/Top/TopStyled.tsx, src/components/Form/stories/Playground.stories.tsx, src/components/SideNav/SideNav.styled.tsx
- Adjusts padding around form sections
- Has form stretch 100% of it's container by default, but introduces a `fullHeight` prop that can be `false` to prevent that
- Ensures field labels are semi-bold
=> MOS-1194 v28 visual bugs

src/components/Field/FormFieldDate/DateField/FormFieldDate.tsx
When picking a date from the datepicker, this ensures the time is always set to midnight if the time field is not enabled. If the time field is enabled, the existing time will be retained.
=> MOS-1193 Sets time to midnight if time field is not enabled

src/components/Typography/Typography.stories.tsx, src/components/Typography/Typography.tsx
Removes the unnecessary `div` that wraps Typography components and updates the story that demonstrates adding custom styles to it using `&&` workaround.
=> MOS-1115 Drop redundant Typography wrapper

src/components/ButtonRow/ButtonRow.styled.tsx, src/components/ButtonRow/ButtonRow.tsx, src/components/ButtonRow/ButtonRowTypes.ts, src/components/DataView/DataViewActionsButtonRow/DataViewActionsButtonRow.tsx, src/components/DataView/DataViewActionsRow/DataViewActionsRow.tsx, src/components/Field/FormFieldUpload/FileCard/FileCard.tsx, src/components/SummaryPageTopComponent/SummaryPageTopComponent.tsx
Deprecates the `gap` row that was available on `ButtonRow`. Now all button rows have a gap of 8px
=> MOS-1194 Minor visual changes

src/components/DataView/DataView.tsx, src/components/PageHeader/PageHeader.styled.tsx
- Increases the padding around the `PageHeader` from 20px to 24px.
- Swaps out horizontal margin used for `DataView` table for padding for consistency.
=> MOS-1194 Spacing adjustments

automation_testing/tests/FormFields/FormFieldMapCoordinates/FormFieldMapCoordinates.spec.ts, src/components/Field/Field.tsx, src/components/Field/FieldTypes.tsx, src/components/Field/FormFieldDate/DateField/FormFieldDate.tsx, src/components/Field/FormFieldMapCoordinates/MapCoordinatesDrawer/MapCoordinatesDrawer.tsx, src/components/Field/FormFieldMatrix/FormFieldMatrix.stories.tsx, src/components/Form/Col/Col.tsx, src/components/Form/Col/ColField.tsx, src/components/Form/Col/ColTypes.ts, src/components/Form/Col/fieldConfigMap.ts, src/components/Form/Form.stories.mdx, src/components/Form/Form.test.tsx, src/components/Form/FormTypes.tsx, src/components/Form/Layout/Layout.tsx, src/components/Form/Layout/layoutUtils.ts, src/components/Form/fieldErrors.ts, src/components/Form/formActions.ts, src/components/Form/formUtils.ts, src/components/Form/state/types.ts, src/components/Form/stories/DrawerForm.stories.tsx, src/components/Form/stories/Validators.stories.tsx, src/utils/array/arrayDifference.ts, src/utils/array/arrayIntersect.ts, src/utils/array/index.ts, src/utils/hooks/index.ts, src/utils/hooks/useFieldErrors/index.ts, src/utils/hooks/useFieldErrors/useFieldErrors.ts
- Introduction of `useFieldErrors` takes a form's dispatch and enables fields to add their own "internal" validators that can throw errors based on their own local state. This function is currently only being consumed by the date field.
- Refactored `Col` into `ColField`.
- Moved form's state.mounted out of state and into a stable reference instead.
- Introduces multiple validation strategies. Each field has a sensible default `validateOn`, but field definitions can take a `validateOn` to specify when strategy to use instead:
- `onChange` validates a field on every change in value
- `onBlur` validates a field when the field loses focus
- `onBlurChange` validates a field when the field loses focus, but then resets the validation when it is next changed
- Improve initial form load …
=> MOS-1131 form system refactor

automation_testing/utils/data/formData.ts, src/components/Form/Form.stories.mdx, src/components/Form/validators.ts
Replaces all occurences of the incorrectly typed "e-mail" text to "email".
=> MOS-1147 Amends  "email" typo

package.json, src/components/Field/FormFieldColorPicker/FormFieldColorPicker.tsx, src/components/Field/FormFieldTextEditor/FormFieldTextEditor.stories.mdx, src/components/Field/FormFieldTextEditor/FormFieldTextEditor.test.tsx, src/components/Field/FormFieldTextEditor/FormFieldTextEditor.tsx, src/components/Form/Form.stories.mdx, yarn.lock
- Triggers blur event when the colour picker is closed.
- Drops the Jodit react wrapper and implements the underlying `jodit` library instead to allow listening for change events whilst avoiding bugs brought with the wrapper.
=> MOS-1131 qa feedback

src/components/Field/FormFieldTextEditor/FormFieldTextEditor.tsx, src/components/Form/formActions.ts
- Employs a workaround to prevent Jodit text editor from losing focus when the value changes
- Considers all fields to be blurred after the form is submitted
=> MOS-1131 QA Feedback 2

src/components/SideNav/SideNav.stories.tsx, src/components/SideNav/SideNav.styled.tsx, src/components/SideNav/SideNav.tsx, src/components/SideNav/SideNavTypes.ts
Enables the `SideNav` link on click handler to prevent the default browser action if no modifier key is used. Also adds support to pass false as an item's `onNav`, which will bypass any `onNav` functionality that may come from `SideNav`
=> MOS-1187 Adds support for default href behaviour

src/components/DataViewFilterDate/DataViewFilterDate.stories.tsx, src/components/Field/FormFieldDate/DateField/FormFieldDate.tsx
- Ensures even invalid dates are stored in internal state, so that when that state is "cleared", the change causes the date's text field to be emptied
- Update the date filter story to prevent negative option counts causing unexpected slicing
=> Mos 1176 Date filter QA rework

automation_testing/pages/Components/Card/CardPlaygroundPage.ts, automation_testing/pages/Components/Content/ContentPage.ts, automation_testing/pages/Components/Form/PlaygroundPage.ts, automation_testing/tests/Components/Content/Content.spec.ts, src/components/Card/Card.styled.tsx, src/components/Card/Card.tsx, src/components/Content/Content.styled.ts, src/components/Content/Content.tsx, src/components/Content/ContentField.tsx, src/components/Content/ContentRow.tsx, src/components/Typography/Typography.styled.ts, src/utils/testIds.ts
- Swaps out the `div` elements used for field labels and content for `dt` and `dd`. Wraps the content component with `dl`
- Adds `data-testid="mos:Content:field"` to each field within the `Content` component for better test locating
- Adds `data-testid="mos:Card:item"` to each item within the `Card` component for better test locating
- Utilises the `SubtitleText` typography component for both `Content` and `Card` components for accessibility and testing
- Updates styling of the `SubtitleText` typography component to match the existing content/card headings
=> MOS-1213 Card accessible elements / test compatible elements and ids

src/components/Button/Button.tsx, src/components/Button/ButtonTypes.tsx, src/components/DataView/DataViewTr/DataViewTr.styled.ts, src/components/DataView/DataViewTr/DataViewTr.tsx
- Modifies the drag handle to use a Mosaic icon button in order to utilise the disabled and focus states
- Allows for a custom component to be passed to the `Button` component that can be used to in place of Materials nested `Button` or `IconButton` components
=> MOS-1218 DnD handle styling and disabled state

src/components/SideNav/SideNav.styled.tsx
This reinstates the `SideNav` section separator that was lost in the MOS-1175 refactor
=> MOS-1228 Section separator

src/components/DataView/DataView.tsx
Remove incorrect usage of `useToggle` for bulk actions and filter those actions based on the checked action handlers that have been provided by the consumer.
=> MOS-1207 Drop useToggle for bulk actions

src/components/DataView/DataView.stories.tsx, src/components/DataView/DataView.tsx, src/components/DataView/DataViewTypes.ts
Adds support to `DataView` component to allow `ref` and `attr` props to be provided by the consumer. A reference to the top level `div` will be forwarded and the attributes provided will be spread onto the top level `div`.
=> MOS-1234 Ref and attrs props for DataView

automation_testing/pages/FormFields/FormFieldImageVideoLinkDocumentBrowsing/FormFieldImageVideoLinkDocumentBrowsingPage.ts, automation_testing/tests/FormFields/FormFieldImageVideoLinkDocumentBrowsing/FormFieldImageVideoLinkDocumentBrowsing.spec.ts, src/components/Button/Button.stories.tsx, src/components/Button/Button.styled.ts, src/components/Button/Button.tsx, src/components/DataView/DataViewDisplayGrid/DataViewDisplayGrid.tsx, src/components/DataViewPrimaryFilter/DataViewPrimaryFilter.tsx, src/components/Field/FormFieldImageVideoLinkDocumentBrowsing/FormFieldImageVideoLinkDocumentBrowsing.tsx, src/components/Field/FormFieldImageVideoLinkDocumentBrowsing/ImageVideoLinkDocumentBrowsing.styled.tsx, src/components/Field/FormFieldImageVideoLinkDocumentBrowsing/ImageVideoLinkDocumentBrowsing.test.tsx, src/components/Field/FormFieldUpload/FileCard/FileCard.tsx, src/components/Field/Label.tsx, src/components/Form/Form.tsx, src/components/Form/FormTypes.tsx, src/components/Form/Top/Top.tsx, src/components/Form/Top/TopStyled.tsx, src/components/Form/Top/TopTypes.ts, src/components/Form/stories/DrawerForm.stories.tsx, src/components/Form/stories/Playground.stories.tsx, src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/Tooltip.styled.tsx, src/components/Tooltip/Tooltip.test.tsx, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/TooltipTypes.tsx, src/components/Tooltip/index.ts, src/components/Tooltip/useTooltip.ts, src/components/Typography/Typography.styled.ts, src/components/Typography/Typography.tsx, src/components/Typography/TypographyTypes.ts
(BREAKING CHANGE) Rehauls the `Tooltip` component, dropping the dependency on Material's `Tooltip` and instead using the underlying `Popper` component directly. `Tooltip` **no longer wraps its anchor**, but instead takes the following required properties:
- `anchorEl` the `HTMLElement` or `SVGElement` that the tooltip should point to
- `open` a `boolean` denoting whether or not the tooltip is currently rendered and visible
- `children`, replacing the old `text` property, which can be any `ReactNode` to be rendered within the tooltip.
There is an optional `useTooltip` hook that can be utilised to make using the `Tooltip` component a little cleaner. It returns `anchorProps` and `tooltipProps` which can be spread into their corresponding components, causing the tooltip to appear when the …
=> MOS-1226 Tooltip component

src/components/Button/Button.styled.ts, src/components/Card/Card.stories.tsx, src/components/CheckboxList/CheckboxList.tsx, src/components/Content/Content.stories.tsx, src/components/DataView/DataViewFilters/DataViewFilters.tsx, src/components/DataViewFilterDate/DataViewFilterDate.tsx, src/components/DataViewFilterMultiselect/DataViewFilterMultiselectDropdownContent.tsx, src/components/Dialog/Dialog.tsx, src/components/Field/FormFieldAddress/Address.test.tsx, src/components/Field/FormFieldAddress/AddressAutocomplete/AddressAutocomplete.tsx, src/components/Field/FormFieldAddress/AddressDrawer/AddressDrawer.tsx, src/components/Field/FormFieldColorPicker/ColorPicker.styled.tsx, src/components/Field/FormFieldDate/DatePicker/DatePicker.styled.tsx, src/components/Field/FormFieldImageUpload/FormFieldImageUpload.tsx, src/components/Field/FormFieldImageVideoLinkDocumentBrowsing/BrowseOption/BrowseOption.tsx, src/components/Field/FormFieldMapCoordinates/Map/Map.tsx, src/components/Field/FormFieldUpload/FormFieldUpload.tsx, src/components/Field/Label.tsx, src/components/Form/stories/DrawerForm.stories.tsx, src/components/Form/validators.ts, src/components/LeftNav/LeftNavDesktop.tsx, src/components/LeftNav/LeftNavFlyout.tsx, src/components/LeftNav/LeftNavItemDesktop.tsx, src/components/LeftNav/NavWrapper.tsx, src/components/Tooltip/Tooltip.styled.tsx, src/transforms/column_transforms.tsx, src/utils/JSONDB.ts, src/utils/date/textIsValidDate.ts, src/utils/hooks/useScrollSpy/useScrollSpy.ts
Ensures imports avoid loading entire libraries:
- Material components are loaded using `@mui/material/*`
- Lodash functions are loaded using `lodash/*`
- Mosaic components and utils are loaded using `@root/components/*`
- Date Fns utils are loaded using `date-fns/*`
=> MOS-1253 Import audit

src/components/DataView/DataView.stories.tsx, src/components/DataView/DataView.tsx, src/components/DataView/DataViewActionsButtonRow/DataViewActionsButtonRow.styled.ts, src/components/DataView/DataViewActionsButtonRow/DataViewActionsButtonRow.tsx, src/components/DataView/DataViewActionsButtonRow/DataViewActionsButtonRowTypes.ts, src/components/DataView/DataViewActionsRow/DataViewActionsRow.styled.ts, src/components/DataView/DataViewDisplayGrid/DataViewDisplayGrid.tsx, src/components/DataView/DataViewDisplayGrid/DataViewDisplayGridTypes.ts, src/components/DataView/DataViewDisplayList/DataViewDisplayList.tsx, src/components/DataView/DataViewDisplayList/DataViewDisplayListTypes.ts, src/components/DataView/DataViewTBody/DataViewTBody.tsx, src/components/DataView/DataViewTBody/DataViewTBodyTypes.ts, src/components/DataView/DataViewTr/DataViewTr.tsx, src/components/DataView/DataViewTr/DataViewTrTypes.ts
With this change, primary and additional row actions will be hidden and disabled (while remaining in the DOM) if any action checkboxes are checked to prevent confusion regarding bulk actions
=> MOS-1241 DataView row actions

src/components/DataView/DataView.stories.tsx, src/components/DataView/DataView.test.tsx, src/components/DataView/DataView.tsx, src/components/DataView/DataViewTypes.ts, src/utils/toggle/useWrappedToggle.ts
- Reinstates toggling mechanism at the `DataView` level for bulk actions and provide appropriate context w/ new tests
- Improved condition for showing DataView's action bar
=> MOS-1257 DataView action toggle fixes and tests

src/components/Tooltip/Tooltip.stories.mdx, src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/Tooltip.styled.tsx, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/TooltipTypes.tsx, src/components/Tooltip/useTooltip.ts
- Ensures the tooltip hook and component can be used in strict TypeScript environments without throwing errors.
- Adds support for a `maxWidth` property that allows the overriding of the default 12rem maximum width.
=> MOS-1259 Tooltip improvements

src/components/Field/FormFieldUpload/FormFieldUpload.stories.tsx, src/components/Field/FormFieldUpload/FormFieldUpload.tsx, src/components/Field/FormFieldUpload/FormFieldUploadTypes.ts
This adds support for individual and cumulative file size limits by introducing two new available input settings for the file upload field. Both properties take the byte limit in the form of a number:
- `maxFileSize` can be used to limit each file uploaded. The `onFileAdd` function will not fire and an error will be displayed beneath the offending file item
- `maxTotalSize` can be used to limit the total cumulative file size. The file(s) selected will not be added to the queue and a snackbar will be displayed to the user reading "Maximum cumulative file size is x" where x is a formatted amount of bytes.
=> MOS-1251 File size limits

.eslintrc.js, automation_testing/tests/Components/Chip/chip.spec.ts, src/components/Checkbox/Checkbox.tsx, src/components/Chip/Chip.styled.ts
Makes the following changes in order to improve form accessibility:
- Reinstates the `Checkbox` ripple to indicate focus.
- Amends `Chip` styling to show visual cues indicating focus where appropriate.
- Adjust eslint to prevent false reports within template strings
=> MOS-1188 Chip accessibility

src/components/Form/formActions.ts
Ensures the form action `submitForm` waits for the result of the asynchronous function `isSubmittable` to correctly return a `{ valid: false }` result.
=> MOS-1266 Form submission not prevented by busy fields

src/components/Form/Form.stories.mdx, src/components/Form/Form.tsx, src/components/Form/FormTypes.tsx, src/components/Form/Section/Section.tsx, src/utils/hooks/useScrollSpy/ScrollSpyTypes.ts, src/utils/hooks/useScrollSpy/useScrollSpy.ts, src/utils/math/animate.ts, src/utils/math/animateTypes.ts
Improves forms with sections user experience by:
- Utilising the `defaultExpanded` property provided by the Material `Accordion` to avoid animating sections when the form is initially mounted.
- Eliminating dual states.
- Adding support for the URL hash to be utilised for section navigation and animating the scroll position to the corresponding section when the form is mounted.
=> MOS-1141 Form section improvements

src/components/Button/Button.tsx
Attaches the `onMouseEnter` and `onMouseLeave` event handlers to the component that wraps the button instead of the button itself, allowing them to be fired even when the button is disabled.
=> MOS-1252 Button mouse events

src/components/Button/Button.stories.tsx, src/components/Button/Button.tsx, src/components/Button/ButtonTypes.tsx, src/utils/toggle/getToggle.ts, src/utils/toggle/useToggle.ts, src/utils/toggle/useWrappedToggle.ts
This employs the toggle mechanic for the `Button` disabled property. It also inverts toggle's behaviour when dealing with arrays of conditions, evaluating in an inverse nature (_some_ instead of _every_) if the `defaultToggle` parameter is `false` instead of `true`.
=> MOS-1254 Button disabled toggle

package.json, src/components/Menu/Menu.tsx, src/components/SummaryPageTopComponent/SummaryPageTopComponent.stories.tsx, yarn.lock
Removes the runtime validation of `Menu` props and drops `jsvalidator` as a dependency since it is no longer in use.
=> MOS-1268 Drop menu props validator

src/components/Form/Form.tsx
Ensures that the URL's hash is updated when a corresponding section's nav item is clicked as well as when it is set as active through scrolling.
=> MOS-1141 Form sections hash change on click

src/components/Field/FormFieldAddress/AddressAutocomplete/AddressAutocomplete.tsx, src/components/Field/FormFieldMapCoordinates/Map/Map.tsx, src/components/Field/FormFieldMapCoordinates/Map/MapWithMarker.tsx, src/components/Field/FormFieldMapCoordinates/MapCoordinatesDrawer/MapCoordinatesDrawer.tsx, src/components/Field/FormFieldMapCoordinates/MapCoordinatesTypes.ts
Ensures the `onBlur` handler is passed down from the map coordinate field's draw to the autocomplete field but also only invoke the `onBlur` handler if it is defined.
=> MOS-1279 Map field thrown error

src/components/Button/Button.styled.ts, src/components/Button/ButtonTypes.tsx, src/components/DataViewFilterDropdownButtons/DataViewFilterDropdownButtons.styled.tsx, src/components/DataViewFilterDropdownButtons/DataViewFilterDropdownButtons.tsx, src/components/DataViewFilterText/DataViewFilterText.styled.ts, src/components/DataViewFilterText/DataViewFilterTextDropdownContent.tsx
Amends the text filter comparison to better fit the interface by matching the comparison dropdown style to the input next to it and rendering it before the term input instead of after it.
=> MOS-1180 DataView text filter UI

src/components/Button/Button.tsx, src/components/Button/ButtonTypes.tsx, src/components/Form/Form.tsx, src/components/Form/FormTypes.tsx, src/components/Form/stories/QuickSubmitForm.stories.tsx
Includes the following to support native HTML form submission behaviour:
- Adds an `onSubmit` property to be provided to `Form` which will pass through to the integrated HTML `form` element
- Adds a `type` property to the `Button` component which will pass through to the integrated HTML `button` element. It can be `"submit"` or `"button"` but will be `"button"` by default.
Default form submission behaviour is always prevented.
=> MOS-1281 Native form submit

src/components/Button/Button.tsx, src/components/Button/ButtonTypes.tsx, src/components/ButtonRow/ButtonRow.tsx, src/components/ButtonRow/ButtonRowTypes.ts, src/components/Form/stories/Playground.stories.tsx
Items that are rendered as a part of the `ButtonRow` component are now given a meaningful key where available:
- If the` ButtonProps` variation is used:
- Optionally accept an `id` property for `ButtonProps`, if provided this will always be used as the `key`
- If no `id` is provided in the `ButtonProps` object, then use a combination of the `label` (if it is a string) and `name` properties.
- If the `children` variation is used, extract the key from each child if it is a valid `ReactElement`
- As a last resort, uses the item’s index.
If button rows are expected to change order throughout their lifecycle, products should not allow the key to fall back to their indexes.
=> MOS-1286 Meaningful ButtonRow item key

src/components/Field/Field.tsx, src/components/Field/FieldTypes.tsx, src/components/Field/FormFieldDate/DateField/FormFieldDate.tsx, src/components/Field/FormFieldDate/DatePicker/DatePicker.tsx, src/components/Field/FormFieldDropdownSingleSelection/FormFieldDropdownSingleSelection.tsx, src/components/Field/FormFieldNumberTable/FormFieldNumberTable.tsx, src/components/Field/FormFieldPhoneSelectionDropdown/FormFieldPhoneSelectionDropdown.tsx, src/components/Field/FormFieldText/FormFieldText.tsx, src/components/Field/FormFieldTextEditor/FormFieldTextEditor.tsx, src/components/Field/FormFieldTime/TimeField/FormFieldTime.tsx, src/components/Field/FormFieldTime/TimePicker/TimePicker.tsx, src/components/Form/Col/ColField.tsx, src/components/Form/Form.stories.mdx, src/components/Form/Form.tsx, src/components/Form/FormTypes.tsx, src/components/Form/stories/QuickSubmitForm.stories.tsx, src/components/Form/useForm/types.ts, src/components/Form/useForm/useForm.ts
Introduces the `autoFocus` property to the `Form` component. If true, once mounted, `Form` will attempt to automatically focus the user's cursor on the first field but only the first field is one of the following field types: `date`, `dropdown`, `numberTable`, `phone`, `text`, `textEditor`, `time`.
=> MOS-1282 Form auto focus

src/components/DataView/DataView.stories.tsx, src/components/DataView/DataView.tsx, src/components/DataView/DataViewDisplayGrid/DataViewDisplayGrid.tsx, src/components/DataView/DataViewDisplayGrid/DataViewDisplayGridTypes.ts, src/components/DataView/DataViewDisplayList/DataViewDisplayList.tsx, src/components/DataView/DataViewDisplayList/DataViewDisplayListTypes.ts, src/components/DataView/DataViewTBody/DataViewTBody.tsx, src/components/DataView/DataViewTBody/DataViewTBodyTypes.ts, src/components/DataView/DataViewTypes.ts
Ensures that the actions column is not rendered if no row-specific actions (primary or additional) are available for any of the rows. This includes cases where no actions are available as a result of their `show` evaluation.
=> MOS-1280 Hides action column when no row actions are available

src/components/Form/Form.tsx, src/components/Form/stories/Playground.stories.tsx, src/components/Form/useForm/reducers.ts, src/components/Form/useForm/types.ts, src/components/Form/useForm/useForm.ts
- Adds populate values for fields that are missing initial data
- Ensures the disable dispatch that is invoked before loading the `getFormValues` result turns on the `loadingInitial` boolean.
=> MOS-1269 Loading state rework

automation_testing/pages/FormFields/FormFieldUpload/FormFieldUploadPage.ts, automation_testing/utils/data/knobs.ts, src/components/Button/Button.styled.ts, src/components/Button/Button.tsx, src/components/Button/ButtonTypes.tsx, src/components/Field/FieldTypes.tsx, src/components/Field/FormFieldUpload/FileCard/FileCard.styled.ts, src/components/Field/FormFieldUpload/FileCard/FileCard.test.tsx, src/components/Field/FormFieldUpload/FileCard/FileCard.tsx, src/components/Field/FormFieldUpload/FileCard/FileCardPending.tsx, src/components/Field/FormFieldUpload/FileCard/FileCardTitle.tsx, src/components/Field/FormFieldUpload/FileCard/FileCardTypes.ts, src/components/Field/FormFieldUpload/FormFieldUpload.stories.tsx, src/components/Field/FormFieldUpload/FormFieldUpload.styled.ts, src/components/Field/FormFieldUpload/FormFieldUpload.tsx, src/components/Field/FormFieldUpload/FormFieldUploadTypes.ts, src/components/Form/Col/fieldConfigMap.ts, src/components/Form/useForm/useForm.ts, src/forms/shared/styledComponents.ts, src/utils/hooks/useHumanSize/index.ts, src/utils/hooks/useHumanSize/useHumanSize.ts, src/utils/hooks/useWhatChanged.ts
Addresses a number of issues regarding the upload field component:
- Modifies the `setFieldValue` method of the form controller and by further extension the `onChange` method that fields recieve, to allow for a callback style value setter. That callback recieves the most up to date value as a reference.
- Merges pending items with current value items and utilises internal data to store both sets as a single array.
- Splits the `FileCard` component into `FileCard` for uploaded items and `FileCardPending` for pending uploads due to their specialised responsibilities.
- Moves the form value cleaner to the default resolver instead of performing value cleaning inside `setFieldValue` making individual field value resolvers responsible for cleaning their values.
- Removes the button onclick hack …
=> MOS-1256 Upload field refactor

src/components/Field/Field.tsx, src/components/Field/FormFieldAddress/AddressDrawer/AddressDrawer.tsx, src/components/Form/Col/ColField.tsx
Adds a `aria-disabled` attribute to field wrappers to denote disabled state and assist with testing.
=> MOS-1301 Field disabled attribute

src/components/DataView/DataView.tsx
Adds the `aria-busy` attribute to `DataView` wrapper which should be used for awaiting within tests over the `.loading` class.
=> MOS-1179 DataView aria-busy attribute

src/components/Field/FormFieldDate/DatePicker/DatePicker.tsx
Forces the date field to use the `DesktopDatePicker` rather than the `DatePicker` MUI component to avoid issues when testing caused by headless browsers not supporting the `(pointer: fine)` media query.
=> MOS-1285 Prevent DatePicker from failing tests

src/components/Field/FormFieldAddress/Address.stories.tsx, src/components/Field/FormFieldAddress/AddressDrawer/AddressDrawer.tsx, src/components/Field/FormFieldAddress/AddressTypes.tsx, src/components/Field/FormFieldAddress/FormFieldAddress.tsx
Refactors the address field slightly to ensure the "Add Address" button doesn't render when there are no more possible address types. Also creates a Kitchen Sink story for easier testing.
=> MOS-1206 Address add button

src/components/Field/Field.tsx, src/components/Field/Label.tsx
For text and text editor fields, where a `maxCharacters` property is provided, there is a _x/y_ figure that appears above the input reflecting the maximum characters and the current amount of characters. With this change, we are utilising this same figure for the advanced selection field to denote how many items can be selected and how many items are currently selected. The figure only appears if `selectLimit` is more than 1.
=> MOS-1181 AdvancedSelection limit figure

src/components/DataViewFilterMultiselect/DataViewFilterMultiselectDropdownContent.tsx, src/components/Field/Field.tsx, src/components/Field/FormFieldAdvancedSelection/AdvancedSelection.stories.tsx, src/components/Field/FormFieldAdvancedSelection/AdvancedSelectionDrawer.tsx, src/components/Field/FormFieldAdvancedSelection/FormFieldAdvancedSelection.tsx
Ensures a negative `selectLimit` input setting imposes no limit. Changes the `selectLimit` Playground story control to use a number input instead of a text input.
=> MOS-1181 Rework

src/components/Form/stories/Playground.stories.tsx
Removes playground prepopulate values control due to the url encoding (or lack) of said values causing errors to be thrown.
=> MOS-1186 Error thrown on Form Playground story

automation_testing/tests/Components/Content/Content.spec.ts, src/components/Field/FormFieldColorPicker/ColorPicker.styled.tsx, src/components/Field/FormFieldColorPicker/ColorPickerTypes.tsx, src/components/Field/FormFieldColorPicker/ColorSelected.tsx, src/components/Field/FormFieldImageUpload/FormFieldImageUpload.styled.ts, src/components/Field/FormFieldImageUpload/FormFieldImageUpload.tsx, src/components/Field/FormFieldImageVideoLinkDocumentBrowsing/BrowseOption/BrowseOption.tsx, src/components/Field/FormFieldImageVideoLinkDocumentBrowsing/ImageVideoLinkDocumentBrowsing.styled.tsx, src/components/Field/FormFieldTextEditor/FormFieldTextEditor.tsx, src/components/Field/FormFieldUpload/FormFieldUpload.tsx
Addresses a number of field types to improve accessibility, specifically ensuring all fields can be focused through the use of keyboard tabbing.
- FormFieldColorPicker: Swaps the containing `div` element for a `button` element.
- FormFieldImageUpload: Enables the button ripple and prevents display of input instead of hiding hacks.
- FormFieldImageVideoLinkDocumentBrowsing: Swaps circular icon `div` elements out for `button` elements.
- FormFieldTextEditor: Provides the tabIndex property to jodit configuration.
- FormFieldUpload: Swaps the "Upload Files" `label` element for a `button` element.
=> MOS-1222 Form tabbing

src/components/Field/FormFieldAddress/AddressCard/AddressCard.styled.tsx, src/components/Field/FormFieldAddress/AddressCard/AddressCard.tsx, src/components/Field/FormFieldImageVideoLinkDocumentBrowsing/FormFieldImageVideoLinkDocumentBrowsing.tsx
Re-enables the Material ripple effect for the address card and asset browser buttons because it's used for indication of element focus.
=> MOS-1222 Rework

src/components/Form/Form.tsx
This ensures the auto focus action is only carried out once the initial load has finished and the form is enabled by using `loadingInitial` and `disabled` as dependencies to the side effect that invokes the focus method.
=> MOS-1315 Autofocus bug

src/components/Button/Button.stories.tsx, src/components/Button/Button.tsx, src/components/ButtonRow/ButtonRow.stories.mdx, src/components/ButtonRow/ButtonRow.stories.tsx, src/components/Form/Row/Row.tsx, src/components/Form/stories/FormWithLayout.stories.tsx, src/components/Menu/Menu.stories.tsx, src/components/SideNav/SideNav.stories.tsx, src/components/SideNav/SideNav.tsx, src/utils/storyUtils.ts
Improves on the show mechanic to ensure wrapping elements are not rendered if there are no items to render within as a result of their `show` evaluation. Specifically:
- Buttons should not render if the `menuItems` property is provided, but there are no menu items to render.
- Form rows should not render if there are no fields and by further extension columns to render within.
- SideNav groups should not render if there are no navigation items to render within.
=> MOS-1312 Toggle wrappers

src/components/DataViewFilterDate/DataViewFilterDate.tsx
The date filter plucks the selected option from the list of provided options and displays the label of that option in the dropdown box. This prevents an error being thrown if the corresponding option is no longer available in those provided.
=> MOS-1225 Date filter invalid option

src/components/Field/FormFieldAddress/AddressDrawer/AddressDrawer.tsx
With a recent edit, when editing an address, the type options were derived from the address being edited as well as the available types from the field itself. This ensures there can be no duplicates when combining the two.
=> MOS-1250 Address types bug

src/components/Content/Content.stories.tsx, src/components/Content/Content.styled.ts, src/components/Content/ContentRow.tsx
Employs a workaround to prevent typography from overflowing outside of individual content item containers. Words will be forced to be broken even if they have no breaking characters.
=> MOS-1320 Content overflow

src/components/Field/Field.tsx, src/components/Form/useForm/useForm.ts, src/components/Form/validators.ts, src/utils/dom/stripTags.ts
This fixes an issue that caused rich text fields to be incorrectly invalidated due to hidden HTML tags that come as a part of the text editor value naturally. We now consistently strip away any HTML tags for not just the character counter, but also as a part of the maximum character validation function.
=> MOS-1325 Editor maximum characters

src/components/Checkbox/Checkbox.tsx, src/components/Checkbox/CheckboxTypes.tsx, src/components/CheckboxList/CheckboxList.tsx, src/components/Field/Field.tsx, src/components/Field/FieldTypes.tsx, src/components/Field/FormFieldAddress/AddressAutocomplete/AddressAutocomplete.tsx, src/components/Field/FormFieldAddress/AddressAutocomplete/AddressAutocompleteTypes.ts, src/components/Field/FormFieldAddress/AddressDrawer/AddressDrawer.tsx, src/components/Field/FormFieldCheckbox/FormFieldCheckbox.tsx, src/components/Field/Label.tsx, src/components/Form/stories/VaryingSections.stories.tsx
- Ensures there is a way for custom fields to render a real `label` element when using `FieldWrapper`.
- Fixes a bug where `FieldWrapper` would use a basic `label` element instead of the one provided by MUI.
- Fixes the custom autocomplete field that is a part of the address field's drawer to ensure its label is fully accessible and corresponds to the autocomplete input.
- Ensures check boxes take on the form field name as their ID, but fallback to a generated ID if it’s not provided or not part of a form field.
- Ensures the varying sections now have uniquely labelled and identified fields.
=> MOS-1277 Rework

src/components/DataView/DataView.tsx, src/components/DataView/DataViewActionsButtonRow/DataViewActionsButtonRowTypes.ts, src/components/DataView/DataViewActionsRow/DataViewActionsRowTypes.ts, src/components/DataView/DataViewBulkActionsButtonsRow/DataViewBulkActionsButtonsRowTypes.ts, src/components/DataView/DataViewDisplayGrid/DataViewDisplayGrid.tsx, src/components/DataView/DataViewDisplayList/DataViewDisplayList.tsx, src/components/DataView/DataViewTBody/DataViewTBody.tsx, src/components/DataView/DataViewTBody/DataViewTBodyTypes.ts, src/components/DataView/DataViewTr/DataViewTr.tsx, src/components/DataView/DataViewTr/DataViewTrTypes.ts, src/components/DataView/DataViewTypes.ts, src/utils/dataViewTools.test.ts, src/utils/dataViewTools.ts
Slightly improves the type of DataView's data property to avoid the need to use `as` when referencing row IDs.
=> MOS-1288 DataView types

src/components/Field/FormFieldAddress/AddressDrawer/AddressDrawer.tsx, src/components/Field/FormFieldAddress/utils/addressUtils.ts
Gives `AddressDrawer` a refactor to squash a number of bugs:
- The address 2 and state fields are now correctly populated in all checked cases, which are a number of both US and UK addresses. Note that there are many world addresses which are not currently supported. It's really a minefield, since the different components given to us by Google depend on the country for which you're querying. For example, as described [here](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform):
- In the UK and in Sweden, the component to display the city is postal_town.
- In Japan, components differ across prefectures.
- Brooklyn and other parts of New York City do not include the city as part of the address. Instead, they use sublocality_level_1.
- The …
=> MOS-1336, MOS-1290 - Address field fixes

src/components/Field/FormFieldTextEditor/JoditEditor.tsx, src/components/FieldWrapper/FieldWrapper.tsx, src/components/Form/validators.ts, src/utils/dom/getHtmlText.ts, src/utils/dom/stripTags.ts
Addresses a number of issues that existed for the text editor form field:
- MOS-1323
- Removes the "add new line" plugin which rendered an incorrectly positioned new line button.
- Removes the "powered by Jodit" text to reduce noise.
- Removes the word and character counter which caused confusion due to the conflicts with Mosaic's character counter.
- MOS-1330
- No longer passes the maximum characters property down to Jodit to avoid conflicts with Mosaic's preferred max character behaviour
- MOS-1339
- Expand on the text editor character count helper to account for eccentricities of HTML whilst still supporting `script` and `style` tags.
=> MOS-1323, MOS-1330, MOS-1339 - Text editor field

src/components/DataView/DataView.stories.tsx, src/components/DataView/DataView.tsx
- Updates the `DataView` playground to ensure the draft primary action is preserved for each row even after reordering.
- Prevents the primary action space preservers from being rendered when the `DataView` is in a grid display mode.
=> MOS-1289 Rework
